SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER DATABASE courtlistener OWNER TO django;

\connect courtlistener

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
SET default_tablespace = '';
SET default_table_access_method = heap;

----------------------------------- SET DEFAULT -----------------------------------------------------

ALTER TABLE ONLY public.audio_audio ALTER COLUMN id SET DEFAULT nextval('public.audio_audio_id_seq'::regclass);
ALTER TABLE ONLY public.audio_audio_panel ALTER COLUMN id SET DEFAULT nextval('public.audio_audio_panel_id_seq'::regclass);
ALTER TABLE ONLY public.audio_audioevent ALTER COLUMN pgh_id SET DEFAULT nextval('public.audio_audioevent_pgh_id_seq'::regclass);
ALTER TABLE ONLY public.audio_audiopanelevent ALTER COLUMN pgh_id SET DEFAULT nextval('public.audio_audiopanelevent_pgh_id_seq'::regclass);
ALTER TABLE ONLY public.people_db_abarating ALTER COLUMN id SET DEFAULT nextval('public.people_db_abarating_id_seq'::regclass);
ALTER TABLE ONLY public.people_db_abaratingevent ALTER COLUMN pgh_id SET DEFAULT nextval('public.people_db_abaratingevent_pgh_id_seq'::regclass);
ALTER TABLE ONLY public.people_db_attorney ALTER COLUMN id SET DEFAULT nextval('public.people_db_attorney_id_seq'::regclass);
ALTER TABLE ONLY public.people_db_attorneyorganization ALTER COLUMN id SET DEFAULT nextval('public.people_db_attorneyorganization_id_seq'::regclass);
ALTER TABLE ONLY public.people_db_attorneyorganizationassociation ALTER COLUMN id SET DEFAULT nextval('public.people_db_attorneyorganizationassociation_id_seq'::regclass);
ALTER TABLE ONLY public.people_db_criminalcomplaint ALTER COLUMN id SET DEFAULT nextval('public.people_db_criminalcomplaint_id_seq'::regclass);
ALTER TABLE ONLY public.people_db_criminalcount ALTER COLUMN id SET DEFAULT nextval('public.people_db_criminalcount_id_seq'::regclass);
ALTER TABLE ONLY public.people_db_education ALTER COLUMN id SET DEFAULT nextval('public.people_db_education_id_seq'::regclass);
ALTER TABLE ONLY public.people_db_educationevent ALTER COLUMN pgh_id SET DEFAULT nextval('public.people_db_educationevent_pgh_id_seq'::regclass);
ALTER TABLE ONLY public.people_db_party ALTER COLUMN id SET DEFAULT nextval('public.people_db_party_id_seq'::regclass);
ALTER TABLE ONLY public.people_db_partytype ALTER COLUMN id SET DEFAULT nextval('public.people_db_partytype_id_seq'::regclass);
ALTER TABLE ONLY public.people_db_person ALTER COLUMN id SET DEFAULT nextval('public.people_db_person_id_seq'::regclass);
ALTER TABLE ONLY public.people_db_person_race ALTER COLUMN id SET DEFAULT nextval('public.people_db_person_race_id_seq'::regclass);
ALTER TABLE ONLY public.people_db_personevent ALTER COLUMN pgh_id SET DEFAULT nextval('public.people_db_personevent_pgh_id_seq'::regclass);
ALTER TABLE ONLY public.people_db_personraceevent ALTER COLUMN pgh_id SET DEFAULT nextval('public.people_db_personraceevent_pgh_id_seq'::regclass);
ALTER TABLE ONLY public.people_db_politicalaffiliation ALTER COLUMN id SET DEFAULT nextval('public.people_db_politicalaffiliation_id_seq'::regclass);
ALTER TABLE ONLY public.people_db_politicalaffiliationevent ALTER COLUMN pgh_id SET DEFAULT nextval('public.people_db_politicalaffiliationevent_pgh_id_seq'::regclass);
ALTER TABLE ONLY public.people_db_position ALTER COLUMN id SET DEFAULT nextval('public.people_db_position_id_seq'::regclass);
ALTER TABLE ONLY public.people_db_positionevent ALTER COLUMN pgh_id SET DEFAULT nextval('public.people_db_positionevent_pgh_id_seq'::regclass);
ALTER TABLE ONLY public.people_db_race ALTER COLUMN id SET DEFAULT nextval('public.people_db_race_id_seq'::regclass);
ALTER TABLE ONLY public.people_db_raceevent ALTER COLUMN pgh_id SET DEFAULT nextval('public.people_db_raceevent_pgh_id_seq'::regclass);
ALTER TABLE ONLY public.people_db_retentionevent ALTER COLUMN id SET DEFAULT nextval('public.people_db_retentionevent_id_seq'::regclass);
ALTER TABLE ONLY public.people_db_retentioneventevent ALTER COLUMN pgh_id SET DEFAULT nextval('public.people_db_retentioneventevent_pgh_id_seq'::regclass);
ALTER TABLE ONLY public.people_db_role ALTER COLUMN id SET DEFAULT nextval('public.people_db_role_id_seq'::regclass);
ALTER TABLE ONLY public.people_db_school ALTER COLUMN id SET DEFAULT nextval('public.people_db_school_id_seq'::regclass);
ALTER TABLE ONLY public.people_db_schoolevent ALTER COLUMN pgh_id SET DEFAULT nextval('public.people_db_schoolevent_pgh_id_seq'::regclass);
ALTER TABLE ONLY public.people_db_source ALTER COLUMN id SET DEFAULT nextval('public.people_db_source_id_seq'::regclass);
ALTER TABLE ONLY public.people_db_sourceevent ALTER COLUMN pgh_id SET DEFAULT nextval('public.people_db_sourceevent_pgh_id_seq'::regclass);
ALTER TABLE ONLY public.search_bankruptcyinformation ALTER COLUMN id SET DEFAULT nextval('public.search_bankruptcyinformation_id_seq'::regclass);
ALTER TABLE ONLY public.search_bankruptcyinformationevent ALTER COLUMN pgh_id SET DEFAULT nextval('public.search_bankruptcyinformationevent_pgh_id_seq'::regclass);
ALTER TABLE ONLY public.search_citation ALTER COLUMN id SET DEFAULT nextval('public.search_citation_id_seq'::regclass);
ALTER TABLE ONLY public.search_citationevent ALTER COLUMN pgh_id SET DEFAULT nextval('public.search_citationevent_pgh_id_seq'::regclass);
ALTER TABLE ONLY public.search_claim ALTER COLUMN id SET DEFAULT nextval('public.search_claim_id_seq'::regclass);
ALTER TABLE ONLY public.search_claim_tags ALTER COLUMN id SET DEFAULT nextval('public.search_claim_tags_id_seq'::regclass);
ALTER TABLE ONLY public.search_claimevent ALTER COLUMN pgh_id SET DEFAULT nextval('public.search_claimevent_pgh_id_seq'::regclass);
ALTER TABLE ONLY public.search_claimhistory ALTER COLUMN id SET DEFAULT nextval('public.search_claimhistory_id_seq'::regclass);
ALTER TABLE ONLY public.search_claimhistoryevent ALTER COLUMN pgh_id SET DEFAULT nextval('public.search_claimhistoryevent_pgh_id_seq'::regclass);
ALTER TABLE ONLY public.search_claimtagsevent ALTER COLUMN pgh_id SET DEFAULT nextval('public.search_claimtagsevent_pgh_id_seq'::regclass);
ALTER TABLE ONLY public.search_courtevent ALTER COLUMN pgh_id SET DEFAULT nextval('public.search_courtevent_pgh_id_seq'::regclass);
ALTER TABLE ONLY public.search_docket ALTER COLUMN id SET DEFAULT nextval('public.search_docket_id_seq'::regclass);
ALTER TABLE ONLY public.search_docket_panel ALTER COLUMN id SET DEFAULT nextval('public.search_docket_panel_id_seq'::regclass);
ALTER TABLE ONLY public.search_docket_tags ALTER COLUMN id SET DEFAULT nextval('public.search_docket_tags_id_seq'::regclass);
ALTER TABLE ONLY public.search_docketentry ALTER COLUMN id SET DEFAULT nextval('public.search_docketentry_id_seq'::regclass);
ALTER TABLE ONLY public.search_docketentry_tags ALTER COLUMN id SET DEFAULT nextval('public.search_docketentry_tags_id_seq'::regclass);
ALTER TABLE ONLY public.search_docketentryevent ALTER COLUMN pgh_id SET DEFAULT nextval('public.search_docketentryevent_pgh_id_seq'::regclass);
ALTER TABLE ONLY public.search_docketentrytagsevent ALTER COLUMN pgh_id SET DEFAULT nextval('public.search_docketentrytagsevent_pgh_id_seq'::regclass);
ALTER TABLE ONLY public.search_docketevent ALTER COLUMN pgh_id SET DEFAULT nextval('public.search_docketevent_pgh_id_seq'::regclass);
ALTER TABLE ONLY public.search_docketpanelevent ALTER COLUMN pgh_id SET DEFAULT nextval('public.search_docketpanelevent_pgh_id_seq'::regclass);
ALTER TABLE ONLY public.search_dockettagsevent ALTER COLUMN pgh_id SET DEFAULT nextval('public.search_dockettagsevent_pgh_id_seq'::regclass);
ALTER TABLE ONLY public.search_opinion ALTER COLUMN id SET DEFAULT nextval('public.search_opinion_id_seq'::regclass);
ALTER TABLE ONLY public.search_opinion_joined_by ALTER COLUMN id SET DEFAULT nextval('public.search_opinion_joined_by_id_seq'::regclass);
ALTER TABLE ONLY public.search_opinioncluster ALTER COLUMN id SET DEFAULT nextval('public.search_opinioncluster_id_seq'::regclass);
ALTER TABLE ONLY public.search_opinioncluster_non_participating_judges ALTER COLUMN id SET DEFAULT nextval('public.search_opinioncluster_non_participating_judges_id_seq'::regclass);
ALTER TABLE ONLY public.search_opinioncluster_panel ALTER COLUMN id SET DEFAULT nextval('public.search_opinioncluster_panel_id_seq'::regclass);
ALTER TABLE ONLY public.search_opinionclusterevent ALTER COLUMN pgh_id SET DEFAULT nextval('public.search_opinionclusterevent_pgh_id_seq'::regclass);
ALTER TABLE ONLY public.search_opinionclusternonparticipatingjudgesevent ALTER COLUMN pgh_id SET DEFAULT nextval('public.search_opinionclusternonparticipatingjudgesevent_pgh_id_seq'::regclass);
ALTER TABLE ONLY public.search_opinionclusterpanelevent ALTER COLUMN pgh_id SET DEFAULT nextval('public.search_opinionclusterpanelevent_pgh_id_seq'::regclass);
ALTER TABLE ONLY public.search_opinionevent ALTER COLUMN pgh_id SET DEFAULT nextval('public.search_opinionevent_pgh_id_seq'::regclass);
ALTER TABLE ONLY public.search_opinionjoinedbyevent ALTER COLUMN pgh_id SET DEFAULT nextval('public.search_opinionjoinedbyevent_pgh_id_seq'::regclass);
ALTER TABLE ONLY public.search_opinionscited ALTER COLUMN id SET DEFAULT nextval('public.search_opinionscited_id_seq'::regclass);
ALTER TABLE ONLY public.search_opinionscitedbyrecapdocument ALTER COLUMN id SET DEFAULT nextval('public.search_opinionscitedbyrecapdocument_id_seq'::regclass);
ALTER TABLE ONLY public.search_originatingcourtinformation ALTER COLUMN id SET DEFAULT nextval('public.search_originatingcourtinformation_id_seq'::regclass);
ALTER TABLE ONLY public.search_originatingcourtinformationevent ALTER COLUMN pgh_id SET DEFAULT nextval('public.search_originatingcourtinformationevent_pgh_id_seq'::regclass);
ALTER TABLE ONLY public.search_parenthetical ALTER COLUMN id SET DEFAULT nextval('public.search_parenthetical_id_seq'::regclass);
ALTER TABLE ONLY public.search_parentheticalgroup ALTER COLUMN id SET DEFAULT nextval('public.search_parentheticalgroup_id_seq'::regclass);
ALTER TABLE ONLY public.search_recapdocument ALTER COLUMN id SET DEFAULT nextval('public.search_recapdocument_id_seq'::regclass);
ALTER TABLE ONLY public.search_recapdocument_tags ALTER COLUMN id SET DEFAULT nextval('public.search_recapdocument_tags_id_seq'::regclass);
ALTER TABLE ONLY public.search_recapdocumentevent ALTER COLUMN pgh_id SET DEFAULT nextval('public.search_recapdocumentevent_pgh_id_seq'::regclass);
ALTER TABLE ONLY public.search_recapdocumenttagsevent ALTER COLUMN pgh_id SET DEFAULT nextval('public.search_recapdocumenttagsevent_pgh_id_seq'::regclass);
ALTER TABLE ONLY public.search_tag ALTER COLUMN id SET DEFAULT nextval('public.search_tag_id_seq'::regclass);
ALTER TABLE ONLY public.search_tagevent ALTER COLUMN pgh_id SET DEFAULT nextval('public.search_tagevent_pgh_id_seq'::regclass);
