SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER DATABASE courtlistener OWNER TO django;

\connect courtlistener

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
SET default_tablespace = '';
SET default_table_access_method = heap;

----------------------------------- PRIMARY KEY -----------------------------------------------------

ALTER TABLE ONLY public.audio_audio_panel ADD CONSTRAINT audio_audio_panel_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.audio_audio ADD CONSTRAINT audio_audio_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.audio_audioevent ADD CONSTRAINT audio_audioevent_pkey PRIMARY KEY (pgh_id);
ALTER TABLE ONLY public.audio_audiopanelevent ADD CONSTRAINT audio_audiopanelevent_pkey PRIMARY KEY (pgh_id);
ALTER TABLE ONLY public.people_db_abarating ADD CONSTRAINT people_db_abarating_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.people_db_abaratingevent ADD CONSTRAINT people_db_abaratingevent_pkey PRIMARY KEY (pgh_id);
ALTER TABLE ONLY public.people_db_attorney ADD CONSTRAINT people_db_attorney_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.people_db_attorneyorganization ADD CONSTRAINT people_db_attorneyorganization_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.people_db_attorneyorganizationassociation ADD CONSTRAINT people_db_attorneyorganizationassociation_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.people_db_criminalcomplaint ADD CONSTRAINT people_db_criminalcomplaint_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.people_db_criminalcount ADD CONSTRAINT people_db_criminalcount_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.people_db_education ADD CONSTRAINT people_db_education_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.people_db_educationevent ADD CONSTRAINT people_db_educationevent_pkey PRIMARY KEY (pgh_id);
ALTER TABLE ONLY public.people_db_party ADD CONSTRAINT people_db_party_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.people_db_partytype ADD CONSTRAINT people_db_partytype_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.people_db_person ADD CONSTRAINT people_db_person_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.people_db_person_race ADD CONSTRAINT people_db_person_race_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.people_db_personevent ADD CONSTRAINT people_db_personevent_pkey PRIMARY KEY (pgh_id);
ALTER TABLE ONLY public.people_db_personraceevent ADD CONSTRAINT people_db_personraceevent_pkey PRIMARY KEY (pgh_id);
ALTER TABLE ONLY public.people_db_politicalaffiliation ADD CONSTRAINT people_db_politicalaffiliation_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.people_db_politicalaffiliationevent ADD CONSTRAINT people_db_politicalaffiliationevent_pkey PRIMARY KEY (pgh_id);
ALTER TABLE ONLY public.people_db_position ADD CONSTRAINT people_db_position_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.people_db_positionevent ADD CONSTRAINT people_db_positionevent_pkey PRIMARY KEY (pgh_id);
ALTER TABLE ONLY public.people_db_race ADD CONSTRAINT people_db_race_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.people_db_raceevent ADD CONSTRAINT people_db_raceevent_pkey PRIMARY KEY (pgh_id);
ALTER TABLE ONLY public.people_db_retentionevent ADD CONSTRAINT people_db_retentionevent_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.people_db_retentioneventevent ADD CONSTRAINT people_db_retentioneventevent_pkey PRIMARY KEY (pgh_id);
ALTER TABLE ONLY public.people_db_role ADD CONSTRAINT people_db_role_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.people_db_school ADD CONSTRAINT people_db_school_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.people_db_schoolevent ADD CONSTRAINT people_db_schoolevent_pkey PRIMARY KEY (pgh_id);
ALTER TABLE ONLY public.people_db_source ADD CONSTRAINT people_db_source_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.people_db_sourceevent ADD CONSTRAINT people_db_sourceevent_pkey PRIMARY KEY (pgh_id);
ALTER TABLE ONLY public.search_bankruptcyinformation ADD CONSTRAINT search_bankruptcyinformation_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.search_bankruptcyinformationevent ADD CONSTRAINT search_bankruptcyinformationevent_pkey PRIMARY KEY (pgh_id);
ALTER TABLE ONLY public.search_citation ADD CONSTRAINT search_citation_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.search_citationevent ADD CONSTRAINT search_citationevent_pkey PRIMARY KEY (pgh_id);
ALTER TABLE ONLY public.search_claim ADD CONSTRAINT search_claim_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.search_claim_tags ADD CONSTRAINT search_claim_tags_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.search_claimevent ADD CONSTRAINT search_claimevent_pkey PRIMARY KEY (pgh_id);
ALTER TABLE ONLY public.search_claimhistory ADD CONSTRAINT search_claimhistory_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.search_claimhistoryevent ADD CONSTRAINT search_claimhistoryevent_pkey PRIMARY KEY (pgh_id);
ALTER TABLE ONLY public.search_claimtagsevent ADD CONSTRAINT search_claimtagsevent_pkey PRIMARY KEY (pgh_id);
ALTER TABLE ONLY public.search_court_appeals_to ADD CONSTRAINT search_court_appeals_to_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.search_court ADD CONSTRAINT search_court_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.search_courtappealstoevent ADD CONSTRAINT search_courtappealstoevent_pkey PRIMARY KEY (pgh_id);
ALTER TABLE ONLY public.search_courtevent ADD CONSTRAINT search_courtevent_pkey PRIMARY KEY (pgh_id);
ALTER TABLE ONLY public.search_courthouse ADD CONSTRAINT search_courthouse_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.search_courthouseevent ADD CONSTRAINT search_courthouseevent_pkey PRIMARY KEY (pgh_id);
ALTER TABLE ONLY public.search_docket_panel ADD CONSTRAINT search_docket_panel_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.search_docket ADD CONSTRAINT search_docket_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.search_docket_tags ADD CONSTRAINT search_docket_tags_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.search_docketentry ADD CONSTRAINT search_docketentry_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.search_docketentry_tags ADD CONSTRAINT search_docketentry_tags_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.search_docketentryevent ADD CONSTRAINT search_docketentryevent_pkey PRIMARY KEY (pgh_id);
ALTER TABLE ONLY public.search_docketentrytagsevent ADD CONSTRAINT search_docketentrytagsevent_pkey PRIMARY KEY (pgh_id);
ALTER TABLE ONLY public.search_docketevent ADD CONSTRAINT search_docketevent_pkey PRIMARY KEY (pgh_id);
ALTER TABLE ONLY public.search_docketpanelevent ADD CONSTRAINT search_docketpanelevent_pkey PRIMARY KEY (pgh_id);
ALTER TABLE ONLY public.search_dockettagsevent ADD CONSTRAINT search_dockettagsevent_pkey PRIMARY KEY (pgh_id);
ALTER TABLE ONLY public.search_opinion_joined_by ADD CONSTRAINT search_opinion_joined_by_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.search_opinion ADD CONSTRAINT search_opinion_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.search_opinioncluster_non_participating_judges ADD CONSTRAINT search_opinioncluster_non_participating_judges_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.search_opinioncluster_panel ADD CONSTRAINT search_opinioncluster_panel_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.search_opinioncluster ADD CONSTRAINT search_opinioncluster_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.search_opinionclusterevent ADD CONSTRAINT search_opinionclusterevent_pkey PRIMARY KEY (pgh_id);
ALTER TABLE ONLY public.search_opinionclusternonparticipatingjudgesevent ADD CONSTRAINT search_opinionclusternonparticipatingjudgesevent_pkey PRIMARY KEY (pgh_id);
ALTER TABLE ONLY public.search_opinionclusterpanelevent ADD CONSTRAINT search_opinionclusterpanelevent_pkey PRIMARY KEY (pgh_id);
ALTER TABLE ONLY public.search_opinionevent ADD CONSTRAINT search_opinionevent_pkey PRIMARY KEY (pgh_id);
ALTER TABLE ONLY public.search_opinionjoinedbyevent ADD CONSTRAINT search_opinionjoinedbyevent_pkey PRIMARY KEY (pgh_id);
ALTER TABLE ONLY public.search_opinionscited ADD CONSTRAINT search_opinionscited_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.search_opinionscitedbyrecapdocument ADD CONSTRAINT search_opinionscitedbyrecapdocument_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.search_originatingcourtinformation ADD CONSTRAINT search_originatingcourtinformation_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.search_originatingcourtinformationevent ADD CONSTRAINT search_originatingcourtinformationevent_pkey PRIMARY KEY (pgh_id);
ALTER TABLE ONLY public.search_parenthetical ADD CONSTRAINT search_parenthetical_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.search_parentheticalgroup ADD CONSTRAINT search_parentheticalgroup_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.search_recapdocument ADD CONSTRAINT search_recapdocument_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.search_recapdocument_tags ADD CONSTRAINT search_recapdocument_tags_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.search_recapdocumentevent ADD CONSTRAINT search_recapdocumentevent_pkey PRIMARY KEY (pgh_id);
ALTER TABLE ONLY public.search_recapdocumenttagsevent ADD CONSTRAINT search_recapdocumenttagsevent_pkey PRIMARY KEY (pgh_id);
ALTER TABLE ONLY public.search_tag ADD CONSTRAINT search_tag_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.search_tagevent ADD CONSTRAINT search_tagevent_pkey PRIMARY KEY (pgh_id);

----------------------------------- UNIQUE -----------------------------------------------------

ALTER TABLE ONLY public.audio_audio_panel ADD CONSTRAINT audio_audio_panel_audio_id_judge_id_key UNIQUE (audio_id, person_id);
ALTER TABLE ONLY public.people_db_attorneyorganizationassociation ADD CONSTRAINT people_db_attorneyorganization_attorney_id_7cda1fb15b747f5_uniq UNIQUE (attorney_id, attorney_organization_id, docket_id);
ALTER TABLE ONLY public.people_db_attorneyorganization ADD CONSTRAINT people_db_attorneyorganization_lookup_key_key UNIQUE (lookup_key);
ALTER TABLE ONLY public.people_db_attorneyorganization ADD CONSTRAINT people_db_attorneyorganization_name_6e4a7d6ba93cb6a6_uniq UNIQUE (name, address1, address2, city, state, zip_code);
ALTER TABLE ONLY public.people_db_partytype ADD CONSTRAINT people_db_partytype_docket_id_345b40b72c694865_uniq UNIQUE (docket_id, party_id, name);
ALTER TABLE ONLY public.people_db_person ADD CONSTRAINT people_db_person_fjc_id_key UNIQUE (fjc_id);
ALTER TABLE ONLY public.people_db_person_race ADD CONSTRAINT people_db_person_race_person_id_race_id_key UNIQUE (person_id, race_id);
ALTER TABLE ONLY public.people_db_race ADD CONSTRAINT people_db_race_race_50897822747d246e_uniq UNIQUE (race);
ALTER TABLE ONLY public.people_db_role ADD CONSTRAINT people_db_role_party_id_73709a165082400a_uniq UNIQUE (party_id, attorney_id, role, docket_id, date_action);
ALTER TABLE ONLY public.search_bankruptcyinformation ADD CONSTRAINT search_bankruptcyinformation_docket_id_key UNIQUE (docket_id);
ALTER TABLE ONLY public.search_citation ADD CONSTRAINT search_citation_cluster_id_7a668830aad411f5_uniq UNIQUE (cluster_id, volume, reporter, page);
ALTER TABLE ONLY public.search_claim_tags ADD CONSTRAINT search_claim_tags_claim_id_tag_id_2f236693_uniq UNIQUE (claim_id, tag_id);
ALTER TABLE ONLY public.search_court_appeals_to ADD CONSTRAINT search_court_appeals_to_from_court_id_to_court_id_006ed7af_uniq UNIQUE (from_court_id, to_court_id);
ALTER TABLE ONLY public.search_court ADD CONSTRAINT search_court_position_key UNIQUE ("position");
ALTER TABLE ONLY public.search_docket ADD CONSTRAINT search_docket_docket_number_7642c6c6dbd04704_uniq UNIQUE (docket_number, pacer_case_id, court_id);
ALTER TABLE ONLY public.search_docket ADD CONSTRAINT search_docket_idb_data_id_key UNIQUE (idb_data_id);
ALTER TABLE ONLY public.search_docket ADD CONSTRAINT search_docket_originating_court_id_key UNIQUE (originating_court_information_id);
ALTER TABLE ONLY public.search_docket_panel ADD CONSTRAINT search_docket_panel_docket_id_person_id_key UNIQUE (docket_id, person_id);
ALTER TABLE ONLY public.search_docket_tags ADD CONSTRAINT search_docket_tags_docket_id_tag_id_key UNIQUE (docket_id, tag_id);
ALTER TABLE ONLY public.search_docketentry_tags ADD CONSTRAINT search_docketentry_tags_docketentry_id_tag_id_key UNIQUE (docketentry_id, tag_id);
ALTER TABLE ONLY public.search_opinion_joined_by ADD CONSTRAINT search_opinion_joined_by_opinion_id_judge_id_key UNIQUE (opinion_id, person_id);
ALTER TABLE ONLY public.search_opinioncluster_non_participating_judges ADD CONSTRAINT search_opinioncluster_non_partic_opinioncluster_id_judge_id_key UNIQUE (opinioncluster_id, person_id);
ALTER TABLE ONLY public.search_opinioncluster_panel ADD CONSTRAINT search_opinioncluster_panel_opinioncluster_id_judge_id_key UNIQUE (opinioncluster_id, person_id);
ALTER TABLE ONLY public.search_opinionscited ADD CONSTRAINT search_opinionscited_citing_opinion_id_7165e96b2aed974f_uniq UNIQUE (citing_opinion_id, cited_opinion_id);
ALTER TABLE ONLY public.search_opinionscitedbyrecapdocument ADD CONSTRAINT search_opinionscitedbyre_citing_document_id_cited_0c621cfd_uniq UNIQUE (citing_document_id, cited_opinion_id);
ALTER TABLE ONLY public.search_recapdocument ADD CONSTRAINT search_recapdocument_docket_entry_id_37b2f4ece60cde00_uniq UNIQUE (docket_entry_id, document_number, attachment_number);
ALTER TABLE ONLY public.search_recapdocument_tags ADD CONSTRAINT search_recapdocument_tags_recapdocument_id_tag_id_key UNIQUE (recapdocument_id, tag_id);
ALTER TABLE ONLY public.search_tag ADD CONSTRAINT search_tag_name_key UNIQUE (name);
