SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER DATABASE courtlistener OWNER TO django;

\connect courtlistener

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
SET default_tablespace = '';
SET default_table_access_method = heap;

----------------------------------- CREATE INDEX  -----------------------------------------------------

CREATE INDEX audio_audio_03b47046 ON public.audio_audio USING btree (local_path_original_file);
CREATE INDEX audio_audio_0b869b2f ON public.audio_audio USING btree (date_blocked);
CREATE INDEX audio_audio_1427d4ab ON public.audio_audio USING btree (docket_id);
CREATE INDEX audio_audio_1cbcfc0f ON public.audio_audio USING btree (download_url);
CREATE INDEX audio_audio_41ddbca9 ON public.audio_audio USING btree (local_path_mp3);
CREATE INDEX audio_audio_5fdb3d66 ON public.audio_audio USING btree (date_modified);
CREATE INDEX audio_audio_61326117 ON public.audio_audio USING btree (blocked);
CREATE INDEX audio_audio_74a89174 ON public.audio_audio USING btree (sha1);
CREATE INDEX audio_audio_c69e55a4 ON public.audio_audio USING btree (date_created);
CREATE INDEX audio_audio_download_url_44408fffeee4f71b_like ON public.audio_audio USING btree (download_url varchar_pattern_ops);
CREATE INDEX audio_audio_local_path_mp3_11f796e4872a9bad_like ON public.audio_audio USING btree (local_path_mp3 varchar_pattern_ops);
CREATE INDEX audio_audio_local_path_original_file_102ce483dde8495d_like ON public.audio_audio USING btree (local_path_original_file varchar_pattern_ops);
CREATE INDEX audio_audio_panel_26f6023f ON public.audio_audio_panel USING btree (audio_id);
CREATE INDEX audio_audio_panel_e7c5d788 ON public.audio_audio_panel USING btree (person_id);
CREATE INDEX audio_audio_sha1_2510d5a8f56f35d4_like ON public.audio_audio USING btree (sha1 varchar_pattern_ops);
CREATE INDEX audio_audioevent_docket_id_d4acad63 ON public.audio_audioevent USING btree (docket_id);
CREATE INDEX audio_audioevent_pgh_context_id_f695da7c ON public.audio_audioevent USING btree (pgh_context_id);
CREATE INDEX audio_audioevent_pgh_obj_id_d4cc0c20 ON public.audio_audioevent USING btree (pgh_obj_id);
CREATE INDEX audio_audiopanelevent_audio_id_3aab9feb ON public.audio_audiopanelevent USING btree (audio_id);
CREATE INDEX audio_audiopanelevent_person_id_0280e6c8 ON public.audio_audiopanelevent USING btree (person_id);
CREATE INDEX audio_audiopanelevent_pgh_context_id_5c5401fc ON public.audio_audiopanelevent USING btree (pgh_context_id);
CREATE INDEX district_court_docket_lookup_idx ON public.search_docket USING btree (court_id, docket_number_core, pacer_case_id);
CREATE INDEX people_db_abarating_5fdb3d66 ON public.people_db_abarating USING btree (date_modified);
CREATE INDEX people_db_abarating_a8452ca7 ON public.people_db_abarating USING btree (person_id);
CREATE INDEX people_db_abarating_c69e55a4 ON public.people_db_abarating USING btree (date_created);
CREATE INDEX people_db_abaratingevent_person_id_976485e8 ON public.people_db_abaratingevent USING btree (person_id);
CREATE INDEX people_db_abaratingevent_pgh_context_id_60d3496a ON public.people_db_abaratingevent USING btree (pgh_context_id);
CREATE INDEX people_db_abaratingevent_pgh_obj_id_0e6a9bc3 ON public.people_db_abaratingevent USING btree (pgh_obj_id);
CREATE INDEX people_db_attorney_5fdb3d66 ON public.people_db_attorney USING btree (date_modified);
CREATE INDEX people_db_attorney_b068931c ON public.people_db_attorney USING btree (name);
CREATE INDEX people_db_attorney_c69e55a4 ON public.people_db_attorney USING btree (date_created);
CREATE INDEX people_db_attorney_name_46d318a02757f6dd_like ON public.people_db_attorney USING btree (name text_pattern_ops);
CREATE INDEX people_db_attorneyorganization_0c0ae404 ON public.people_db_attorneyorganization USING btree (zip_code);
CREATE INDEX people_db_attorneyorganization_4ed5d2ea ON public.people_db_attorneyorganization USING btree (city);
CREATE INDEX people_db_attorneyorganization_5fdb3d66 ON public.people_db_attorneyorganization USING btree (date_modified);
CREATE INDEX people_db_attorneyorganization_81e70cb1 ON public.people_db_attorneyorganization USING btree (address1);
CREATE INDEX people_db_attorneyorganization_9ed39e2e ON public.people_db_attorneyorganization USING btree (state);
CREATE INDEX people_db_attorneyorganization_address1_403814857b548870_like ON public.people_db_attorneyorganization USING btree (address1 text_pattern_ops);
CREATE INDEX people_db_attorneyorganization_address2_403814857b4403d3_like ON public.people_db_attorneyorganization USING btree (address2 text_pattern_ops);
CREATE INDEX people_db_attorneyorganization_b068931c ON public.people_db_attorneyorganization USING btree (name);
CREATE INDEX people_db_attorneyorganization_c69e55a4 ON public.people_db_attorneyorganization USING btree (date_created);
CREATE INDEX people_db_attorneyorganization_city_2a5498a19c997008_like ON public.people_db_attorneyorganization USING btree (city text_pattern_ops);
CREATE INDEX people_db_attorneyorganization_f669f8e9 ON public.people_db_attorneyorganization USING btree (address2);
CREATE INDEX people_db_attorneyorganization_lookup_key_4723770634841e39_like ON public.people_db_attorneyorganization USING btree (lookup_key text_pattern_ops);
CREATE INDEX people_db_attorneyorganization_name_eddcefc5b671344_like ON public.people_db_attorneyorganization USING btree (name text_pattern_ops);
CREATE INDEX people_db_attorneyorganization_state_18fe99f5bf671255_like ON public.people_db_attorneyorganization USING btree (state varchar_pattern_ops);
CREATE INDEX people_db_attorneyorganization_zip_code_66632293e4093e4e_like ON public.people_db_attorneyorganization USING btree (zip_code varchar_pattern_ops);
CREATE INDEX people_db_attorneyorganizationassociation_1427d4ab ON public.people_db_attorneyorganizationassociation USING btree (docket_id);
CREATE INDEX people_db_attorneyorganizationassociation_9f99f769 ON public.people_db_attorneyorganizationassociation USING btree (attorney_id);
CREATE INDEX people_db_attorneyorganizationassociation_a2c8783d ON public.people_db_attorneyorganizationassociation USING btree (attorney_organization_id);
CREATE INDEX people_db_criminalcomplaint_4edc179c ON public.people_db_criminalcomplaint USING btree (party_type_id);
CREATE INDEX people_db_criminalcount_4edc179c ON public.people_db_criminalcount USING btree (party_type_id);
CREATE INDEX people_db_education_5fc7164b ON public.people_db_education USING btree (school_id);
CREATE INDEX people_db_education_5fdb3d66 ON public.people_db_education USING btree (date_modified);
CREATE INDEX people_db_education_a8452ca7 ON public.people_db_education USING btree (person_id);
CREATE INDEX people_db_education_c69e55a4 ON public.people_db_education USING btree (date_created);
CREATE INDEX people_db_educationevent_person_id_86892be3 ON public.people_db_educationevent USING btree (person_id);
CREATE INDEX people_db_educationevent_pgh_context_id_93dac561 ON public.people_db_educationevent USING btree (pgh_context_id);
CREATE INDEX people_db_educationevent_pgh_obj_id_242c5dea ON public.people_db_educationevent USING btree (pgh_obj_id);
CREATE INDEX people_db_educationevent_school_id_5d83b038 ON public.people_db_educationevent USING btree (school_id);
CREATE INDEX people_db_party_5fdb3d66 ON public.people_db_party USING btree (date_modified);
CREATE INDEX people_db_party_b068931c ON public.people_db_party USING btree (name);
CREATE INDEX people_db_party_bb2cb5a6 ON public.people_db_party USING btree (extra_info);
CREATE INDEX people_db_party_c69e55a4 ON public.people_db_party USING btree (date_created);
CREATE INDEX people_db_party_extra_info_7a50cbcc44fd5d7a_like ON public.people_db_party USING btree (extra_info text_pattern_ops);
CREATE INDEX people_db_party_name_3d12b76fe7f0ae1c_like ON public.people_db_party USING btree (name text_pattern_ops);
CREATE INDEX people_db_partytype_1427d4ab ON public.people_db_partytype USING btree (docket_id);
CREATE INDEX people_db_partytype_2c662395 ON public.people_db_partytype USING btree (party_id);
CREATE INDEX people_db_partytype_b068931c ON public.people_db_partytype USING btree (name);
CREATE INDEX people_db_partytype_bb2cb5a6 ON public.people_db_partytype USING btree (extra_info);
CREATE INDEX people_db_partytype_name_4cb81702de26fee8_like ON public.people_db_partytype USING btree (name varchar_pattern_ops);
CREATE INDEX people_db_person_2dbcba41 ON public.people_db_person USING btree (slug);
CREATE INDEX people_db_person_3c6ec45e ON public.people_db_person USING btree (is_alias_of_id);
CREATE INDEX people_db_person_5fdb3d66 ON public.people_db_person USING btree (date_modified);
CREATE INDEX people_db_person_c69e55a4 ON public.people_db_person USING btree (date_created);
CREATE INDEX people_db_person_c943ec03 ON public.people_db_person USING btree (name_last);
CREATE INDEX people_db_person_e489b049 ON public.people_db_person USING btree (ftm_total_received);
CREATE INDEX people_db_person_name_last_2c38f190d58b7eba_like ON public.people_db_person USING btree (name_last varchar_pattern_ops);
CREATE INDEX people_db_person_race_3f2f3687 ON public.people_db_person_race USING btree (race_id);
CREATE INDEX people_db_person_race_a8452ca7 ON public.people_db_person_race USING btree (person_id);
CREATE INDEX people_db_person_slug_10074d278f243e42_like ON public.people_db_person USING btree (slug varchar_pattern_ops);
CREATE INDEX people_db_personevent_is_alias_of_id_dff0de5e ON public.people_db_personevent USING btree (is_alias_of_id);
CREATE INDEX people_db_personevent_pgh_context_id_8c18edc2 ON public.people_db_personevent USING btree (pgh_context_id);
CREATE INDEX people_db_personevent_pgh_obj_id_3a44721c ON public.people_db_personevent USING btree (pgh_obj_id);
CREATE INDEX people_db_personraceevent_person_id_000fffe6 ON public.people_db_personraceevent USING btree (person_id);
CREATE INDEX people_db_personraceevent_pgh_context_id_6e61479f ON public.people_db_personraceevent USING btree (pgh_context_id);
CREATE INDEX people_db_personraceevent_race_id_ec19c576 ON public.people_db_personraceevent USING btree (race_id);
CREATE INDEX people_db_politicalaffiliation_5fdb3d66 ON public.people_db_politicalaffiliation USING btree (date_modified);
CREATE INDEX people_db_politicalaffiliation_a8452ca7 ON public.people_db_politicalaffiliation USING btree (person_id);
CREATE INDEX people_db_politicalaffiliation_c69e55a4 ON public.people_db_politicalaffiliation USING btree (date_created);
CREATE INDEX people_db_politicalaffiliationevent_person_id_968b07ce ON public.people_db_politicalaffiliationevent USING btree (person_id);
CREATE INDEX people_db_politicalaffiliationevent_pgh_context_id_dfbcdb75 ON public.people_db_politicalaffiliationevent USING btree (pgh_context_id);
CREATE INDEX people_db_politicalaffiliationevent_pgh_obj_id_c98e3cf6 ON public.people_db_politicalaffiliationevent USING btree (pgh_obj_id);
CREATE INDEX people_db_position_0ce67364 ON public.people_db_position USING btree (date_start);
CREATE INDEX people_db_position_1301727a ON public.people_db_position USING btree (date_elected);
CREATE INDEX people_db_position_22b8ff35 ON public.people_db_position USING btree (appointer_id);
CREATE INDEX people_db_position_2a1c0b55 ON public.people_db_position USING btree (date_confirmation);
CREATE INDEX people_db_position_43e12164 ON public.people_db_position USING btree (date_judicial_committee_action);
CREATE INDEX people_db_position_5fc7164b ON public.people_db_position USING btree (school_id);
CREATE INDEX people_db_position_5fdb3d66 ON public.people_db_position USING btree (date_modified);
CREATE INDEX people_db_position_7a183bc6 ON public.people_db_position USING btree (date_recess_appointment);
CREATE INDEX people_db_position_7a46e69c ON public.people_db_position USING btree (court_id);
CREATE INDEX people_db_position_a2289cae ON public.people_db_position USING btree (date_referred_to_judicial_committee);
CREATE INDEX people_db_position_a7ad19f8 ON public.people_db_position USING btree (date_nominated);
CREATE INDEX people_db_position_a8452ca7 ON public.people_db_position USING btree (person_id);
CREATE INDEX people_db_position_a9962d2d ON public.people_db_position USING btree (date_retirement);
CREATE INDEX people_db_position_b070f947 ON public.people_db_position USING btree (predecessor_id);
CREATE INDEX people_db_position_c69e55a4 ON public.people_db_position USING btree (date_created);
CREATE INDEX people_db_position_court_id_7141eee9b516a894_like ON public.people_db_position USING btree (court_id varchar_pattern_ops);
CREATE INDEX people_db_position_d32bfe21 ON public.people_db_position USING btree (date_termination);
CREATE INDEX people_db_position_eae0a89e ON public.people_db_position USING btree (supervisor_id);
CREATE INDEX people_db_position_ed551732 ON public.people_db_position USING btree (date_hearing);
CREATE INDEX people_db_positionevent_appointer_id_9a1a141d ON public.people_db_positionevent USING btree (appointer_id);
CREATE INDEX people_db_positionevent_court_id_c27f27bf ON public.people_db_positionevent USING btree (court_id);
CREATE INDEX people_db_positionevent_court_id_c27f27bf_like ON public.people_db_positionevent USING btree (court_id varchar_pattern_ops);
CREATE INDEX people_db_positionevent_person_id_b48e5d5c ON public.people_db_positionevent USING btree (person_id);
CREATE INDEX people_db_positionevent_pgh_context_id_91818e04 ON public.people_db_positionevent USING btree (pgh_context_id);
CREATE INDEX people_db_positionevent_pgh_obj_id_e37b1a99 ON public.people_db_positionevent USING btree (pgh_obj_id);
CREATE INDEX people_db_positionevent_predecessor_id_a183a0e5 ON public.people_db_positionevent USING btree (predecessor_id);
CREATE INDEX people_db_positionevent_school_id_8435314e ON public.people_db_positionevent USING btree (school_id);
CREATE INDEX people_db_positionevent_supervisor_id_d1b31dbb ON public.people_db_positionevent USING btree (supervisor_id);
CREATE INDEX people_db_raceevent_pgh_context_id_590006cf ON public.people_db_raceevent USING btree (pgh_context_id);
CREATE INDEX people_db_raceevent_pgh_obj_id_f7ec57e8 ON public.people_db_raceevent USING btree (pgh_obj_id);
CREATE INDEX people_db_retentionevent_4e6b5ce9 ON public.people_db_retentionevent USING btree (date_retention);
CREATE INDEX people_db_retentionevent_5fdb3d66 ON public.people_db_retentionevent USING btree (date_modified);
CREATE INDEX people_db_retentionevent_bce5bd07 ON public.people_db_retentionevent USING btree (position_id);
CREATE INDEX people_db_retentionevent_c69e55a4 ON public.people_db_retentionevent USING btree (date_created);
CREATE INDEX people_db_retentioneventevent_pgh_context_id_81f7850b ON public.people_db_retentioneventevent USING btree (pgh_context_id);
CREATE INDEX people_db_retentioneventevent_pgh_obj_id_902d74ea ON public.people_db_retentioneventevent USING btree (pgh_obj_id);
CREATE INDEX people_db_retentioneventevent_position_id_96c16566 ON public.people_db_retentioneventevent USING btree (position_id);
CREATE INDEX people_db_role_1427d4ab ON public.people_db_role USING btree (docket_id);
CREATE INDEX people_db_role_29a7e964 ON public.people_db_role USING btree (role);
CREATE INDEX people_db_role_2c662395 ON public.people_db_role USING btree (party_id);
CREATE INDEX people_db_role_9f99f769 ON public.people_db_role USING btree (attorney_id);
CREATE INDEX people_db_school_3c6ec45e ON public.people_db_school USING btree (is_alias_of_id);
CREATE INDEX people_db_school_5fdb3d66 ON public.people_db_school USING btree (date_modified);
CREATE INDEX people_db_school_b068931c ON public.people_db_school USING btree (name);
CREATE INDEX people_db_school_c69e55a4 ON public.people_db_school USING btree (date_created);
CREATE INDEX people_db_school_ffef75ef ON public.people_db_school USING btree (ein);
CREATE INDEX people_db_school_name_55359da037ff6cd5_like ON public.people_db_school USING btree (name varchar_pattern_ops);
CREATE INDEX people_db_schoolevent_is_alias_of_id_4c4332d7 ON public.people_db_schoolevent USING btree (is_alias_of_id);
CREATE INDEX people_db_schoolevent_pgh_context_id_b32512bd ON public.people_db_schoolevent USING btree (pgh_context_id);
CREATE INDEX people_db_schoolevent_pgh_obj_id_57bf2a67 ON public.people_db_schoolevent USING btree (pgh_obj_id);
CREATE INDEX people_db_source_5fdb3d66 ON public.people_db_source USING btree (date_modified);
CREATE INDEX people_db_source_a8452ca7 ON public.people_db_source USING btree (person_id);
CREATE INDEX people_db_source_c69e55a4 ON public.people_db_source USING btree (date_created);
CREATE INDEX people_db_sourceevent_person_id_f32cf8b3 ON public.people_db_sourceevent USING btree (person_id);
CREATE INDEX people_db_sourceevent_pgh_context_id_6bf9fb8f ON public.people_db_sourceevent USING btree (pgh_context_id);
CREATE INDEX people_db_sourceevent_pgh_obj_id_c37b1d95 ON public.people_db_sourceevent USING btree (pgh_obj_id);
CREATE INDEX search_bankruptcyinformation_date_created_60f180b0 ON public.search_bankruptcyinformation USING btree (date_created);
CREATE INDEX search_bankruptcyinformation_date_modified_c1b76dd9 ON public.search_bankruptcyinformation USING btree (date_modified);
CREATE INDEX search_bankruptcyinformationevent_docket_id_e6ca7d29 ON public.search_bankruptcyinformationevent USING btree (docket_id);
CREATE INDEX search_bankruptcyinformationevent_pgh_context_id_5e7bd505 ON public.search_bankruptcyinformationevent USING btree (pgh_context_id);
CREATE INDEX search_bankruptcyinformationevent_pgh_obj_id_73c1db25 ON public.search_bankruptcyinformationevent USING btree (pgh_obj_id);
CREATE INDEX search_cita_volume_464334_idx ON public.search_citation USING btree (volume, reporter);
CREATE INDEX search_cita_volume_92c344_idx ON public.search_citation USING btree (volume, reporter, page);
CREATE INDEX search_citation_966557f0 ON public.search_citation USING btree (reporter);
CREATE INDEX search_citation_a97b1c12 ON public.search_citation USING btree (cluster_id);
CREATE INDEX search_citation_reporter_1b48f47a0886ffdd_like ON public.search_citation USING btree (reporter text_pattern_ops);
CREATE INDEX search_citationevent_cluster_id_3cc4bdde ON public.search_citationevent USING btree (cluster_id);
CREATE INDEX search_citationevent_pgh_context_id_a721796b ON public.search_citationevent USING btree (pgh_context_id);
CREATE INDEX search_citationevent_pgh_obj_id_74bef0e4 ON public.search_citationevent USING btree (pgh_obj_id);
CREATE INDEX search_claim_claim_number_263236b3 ON public.search_claim USING btree (claim_number);
CREATE INDEX search_claim_claim_number_263236b3_like ON public.search_claim USING btree (claim_number varchar_pattern_ops);
CREATE INDEX search_claim_date_created_8c2e998c ON public.search_claim USING btree (date_created);
CREATE INDEX search_claim_date_modified_f38130a2 ON public.search_claim USING btree (date_modified);
CREATE INDEX search_claim_docket_id_b37171a9 ON public.search_claim USING btree (docket_id);
CREATE INDEX search_claim_tags_claim_id_2cf554b5 ON public.search_claim_tags USING btree (claim_id);
CREATE INDEX search_claim_tags_tag_id_73b6bd4d ON public.search_claim_tags USING btree (tag_id);
CREATE INDEX search_claimevent_docket_id_b016b91c ON public.search_claimevent USING btree (docket_id);
CREATE INDEX search_claimevent_pgh_context_id_421c9863 ON public.search_claimevent USING btree (pgh_context_id);
CREATE INDEX search_claimevent_pgh_obj_id_eb8bb005 ON public.search_claimevent USING btree (pgh_obj_id);
CREATE INDEX search_claimhistory_claim_id_e130e572 ON public.search_claimhistory USING btree (claim_id);
CREATE INDEX search_claimhistory_date_created_586d545e ON public.search_claimhistory USING btree (date_created);
CREATE INDEX search_claimhistory_date_modified_5f6ec339 ON public.search_claimhistory USING btree (date_modified);
CREATE INDEX search_claimhistory_document_number_6316c155 ON public.search_claimhistory USING btree (document_number);
CREATE INDEX search_claimhistory_document_number_6316c155_like ON public.search_claimhistory USING btree (document_number varchar_pattern_ops);
CREATE INDEX search_claimhistory_is_free_on_pacer_81332a2c ON public.search_claimhistory USING btree (is_free_on_pacer);
CREATE INDEX search_claimhistoryevent_claim_id_a256e51f ON public.search_claimhistoryevent USING btree (claim_id);
CREATE INDEX search_claimhistoryevent_pgh_context_id_fbccd42a ON public.search_claimhistoryevent USING btree (pgh_context_id);
CREATE INDEX search_claimhistoryevent_pgh_obj_id_51dc3876 ON public.search_claimhistoryevent USING btree (pgh_obj_id);
CREATE INDEX search_claimtagsevent_claim_id_34146335 ON public.search_claimtagsevent USING btree (claim_id);
CREATE INDEX search_claimtagsevent_pgh_context_id_bb236d3a ON public.search_claimtagsevent USING btree (pgh_context_id);
CREATE INDEX search_claimtagsevent_tag_id_fdeb7331 ON public.search_claimtagsevent USING btree (tag_id);
CREATE INDEX search_court_5fdb3d66 ON public.search_court USING btree (date_modified);
CREATE INDEX search_court_appeals_to_from_court_id_fb09cc1a ON public.search_court_appeals_to USING btree (from_court_id);
CREATE INDEX search_court_appeals_to_from_court_id_fb09cc1a_like ON public.search_court_appeals_to USING btree (from_court_id varchar_pattern_ops);
CREATE INDEX search_court_appeals_to_to_court_id_49ac3d9c ON public.search_court_appeals_to USING btree (to_court_id);
CREATE INDEX search_court_appeals_to_to_court_id_49ac3d9c_like ON public.search_court_appeals_to USING btree (to_court_id varchar_pattern_ops);
CREATE INDEX search_court_id_28e1a61bd5ca39cc_like ON public.search_court USING btree (id varchar_pattern_ops);
CREATE INDEX search_court_parent_court_id_51ba1d28 ON public.search_court USING btree (parent_court_id);
CREATE INDEX search_court_parent_court_id_51ba1d28_like ON public.search_court USING btree (parent_court_id varchar_pattern_ops);
CREATE INDEX search_courtappealstoevent_from_court_id_75784b8f ON public.search_courtappealstoevent USING btree (from_court_id);
CREATE INDEX search_courtappealstoevent_from_court_id_75784b8f_like ON public.search_courtappealstoevent USING btree (from_court_id varchar_pattern_ops);
CREATE INDEX search_courtappealstoevent_pgh_context_id_e65511b3 ON public.search_courtappealstoevent USING btree (pgh_context_id);
CREATE INDEX search_courtappealstoevent_to_court_id_5540ee1b ON public.search_courtappealstoevent USING btree (to_court_id);
CREATE INDEX search_courtappealstoevent_to_court_id_5540ee1b_like ON public.search_courtappealstoevent USING btree (to_court_id varchar_pattern_ops);
CREATE INDEX search_courtevent_parent_court_id_342036cc ON public.search_courtevent USING btree (parent_court_id);
CREATE INDEX search_courtevent_parent_court_id_342036cc_like ON public.search_courtevent USING btree (parent_court_id varchar_pattern_ops);
CREATE INDEX search_courtevent_pgh_context_id_7a93b57e ON public.search_courtevent USING btree (pgh_context_id);
CREATE INDEX search_courtevent_pgh_obj_id_a86c8348 ON public.search_courtevent USING btree (pgh_obj_id);
CREATE INDEX search_courtevent_pgh_obj_id_a86c8348_like ON public.search_courtevent USING btree (pgh_obj_id varchar_pattern_ops);
CREATE INDEX search_courthouse_court_id_6528f572 ON public.search_courthouse USING btree (court_id);
CREATE INDEX search_courthouse_court_id_6528f572_like ON public.search_courthouse USING btree (court_id varchar_pattern_ops);
CREATE INDEX search_courthouseevent_court_id_ecdd5b8a ON public.search_courthouseevent USING btree (court_id);
CREATE INDEX search_courthouseevent_court_id_ecdd5b8a_like ON public.search_courthouseevent USING btree (court_id varchar_pattern_ops);
CREATE INDEX search_courthouseevent_pgh_context_id_affccfe3 ON public.search_courthouseevent USING btree (pgh_context_id);
CREATE INDEX search_courthouseevent_pgh_obj_id_2bdd6824 ON public.search_courthouseevent USING btree (pgh_obj_id);
CREATE INDEX search_dock_court_i_a043ae_idx ON public.search_docket USING btree (court_id, id);
CREATE INDEX search_dock_recap_s_306ab9_idx ON public.search_docketentry USING btree (recap_sequence_number, entry_number);
CREATE INDEX search_docket_02c1725c ON public.search_docket USING btree (assigned_to_id);
CREATE INDEX search_docket_0b869b2f ON public.search_docket USING btree (date_blocked);
CREATE INDEX search_docket_34894a03 ON public.search_docket USING btree (pacer_case_id);
CREATE INDEX search_docket_5fdb3d66 ON public.search_docket USING btree (date_modified);
CREATE INDEX search_docket_64cdae4d ON public.search_docket USING btree (referred_to_id);
CREATE INDEX search_docket_695b63bb ON public.search_docket USING btree (appeal_from_id);
CREATE INDEX search_docket_6c91ba55 ON public.search_docket USING btree (docket_number_core);
CREATE INDEX search_docket_7a46e69c ON public.search_docket USING btree (court_id);
CREATE INDEX search_docket_c69e55a4 ON public.search_docket USING btree (date_created);
CREATE INDEX search_docket_court_id_2d2438b2594e74ba_like ON public.search_docket USING btree (court_id varchar_pattern_ops);
CREATE INDEX search_docket_docket_number_4af29e98dca38326_uniq ON public.search_docket USING btree (docket_number);
CREATE INDEX search_docket_docket_number_core_713b7b04e01f11d7_like ON public.search_docket USING btree (docket_number_core varchar_pattern_ops);
CREATE INDEX search_docket_panel_1427d4ab ON public.search_docket_panel USING btree (docket_id);
CREATE INDEX search_docket_panel_a8452ca7 ON public.search_docket_panel USING btree (person_id);
CREATE INDEX search_docket_tags_1427d4ab ON public.search_docket_tags USING btree (docket_id);
CREATE INDEX search_docket_tags_76f094bc ON public.search_docket_tags USING btree (tag_id);
CREATE INDEX search_docketentry_1427d4ab ON public.search_docketentry USING btree (docket_id);
CREATE INDEX search_docketentry_5fdb3d66 ON public.search_docketentry USING btree (date_modified);
CREATE INDEX search_docketentry_c69e55a4 ON public.search_docketentry USING btree (date_created);
CREATE INDEX search_docketentry_tags_76f094bc ON public.search_docketentry_tags USING btree (tag_id);
CREATE INDEX search_docketentry_tags_b02d089e ON public.search_docketentry_tags USING btree (docketentry_id);
CREATE INDEX search_docketentryevent_docket_id_469ad4c0 ON public.search_docketentryevent USING btree (docket_id);
CREATE INDEX search_docketentryevent_pgh_context_id_1bd9c36d ON public.search_docketentryevent USING btree (pgh_context_id);
CREATE INDEX search_docketentryevent_pgh_obj_id_584ac554 ON public.search_docketentryevent USING btree (pgh_obj_id);
CREATE INDEX search_docketentrytagsevent_docketentry_id_1aa64197 ON public.search_docketentrytagsevent USING btree (docketentry_id);
CREATE INDEX search_docketentrytagsevent_pgh_context_id_f91c4367 ON public.search_docketentrytagsevent USING btree (pgh_context_id);
CREATE INDEX search_docketentrytagsevent_tag_id_9d769fa5 ON public.search_docketentrytagsevent USING btree (tag_id);
CREATE INDEX search_docketevent_appeal_from_id_388367c7 ON public.search_docketevent USING btree (appeal_from_id);
CREATE INDEX search_docketevent_appeal_from_id_388367c7_like ON public.search_docketevent USING btree (appeal_from_id varchar_pattern_ops);
CREATE INDEX search_docketevent_assigned_to_id_13bac477 ON public.search_docketevent USING btree (assigned_to_id);
CREATE INDEX search_docketevent_court_id_c6baeb82 ON public.search_docketevent USING btree (court_id);
CREATE INDEX search_docketevent_court_id_c6baeb82_like ON public.search_docketevent USING btree (court_id varchar_pattern_ops);
CREATE INDEX search_docketevent_idb_data_id_62179a0f ON public.search_docketevent USING btree (idb_data_id);
CREATE INDEX search_docketevent_originating_court_information_id_47acc418 ON public.search_docketevent USING btree (originating_court_information_id);
CREATE INDEX search_docketevent_pgh_context_id_72300038 ON public.search_docketevent USING btree (pgh_context_id);
CREATE INDEX search_docketevent_pgh_obj_id_5d06013e ON public.search_docketevent USING btree (pgh_obj_id);
CREATE INDEX search_docketevent_referred_to_id_ba58a272 ON public.search_docketevent USING btree (referred_to_id);
CREATE INDEX search_docketpanelevent_docket_id_1a9e206c ON public.search_docketpanelevent USING btree (docket_id);
CREATE INDEX search_docketpanelevent_person_id_97094b3d ON public.search_docketpanelevent USING btree (person_id);
CREATE INDEX search_docketpanelevent_pgh_context_id_03019aa7 ON public.search_docketpanelevent USING btree (pgh_context_id);
CREATE INDEX search_dockettagsevent_docket_id_b1874f82 ON public.search_dockettagsevent USING btree (docket_id);
CREATE INDEX search_dockettagsevent_pgh_context_id_69b62450 ON public.search_dockettagsevent USING btree (pgh_context_id);
CREATE INDEX search_dockettagsevent_tag_id_728990f4 ON public.search_dockettagsevent USING btree (tag_id);
CREATE INDEX search_opin_depth_3307bd_idx ON public.search_opinionscitedbyrecapdocument USING btree (depth);
CREATE INDEX search_opinion_1cbcfc0f ON public.search_opinion USING btree (download_url);
CREATE INDEX search_opinion_4f331e2f ON public.search_opinion USING btree (author_id);
CREATE INDEX search_opinion_5fdb3d66 ON public.search_opinion USING btree (date_modified);
CREATE INDEX search_opinion_71485e76 ON public.search_opinion USING btree (local_path);
CREATE INDEX search_opinion_74a89174 ON public.search_opinion USING btree (sha1);
CREATE INDEX search_opinion_a97b1c12 ON public.search_opinion USING btree (cluster_id);
CREATE INDEX search_opinion_bded6737 ON public.search_opinion USING btree (extracted_by_ocr);
CREATE INDEX search_opinion_c69e55a4 ON public.search_opinion USING btree (date_created);
CREATE INDEX search_opinion_download_url_3b11b165f23bc568_like ON public.search_opinion USING btree (download_url varchar_pattern_ops);
CREATE INDEX search_opinion_joined_by_8a09c46f ON public.search_opinion_joined_by USING btree (opinion_id);
CREATE INDEX search_opinion_joined_by_e7c5d788 ON public.search_opinion_joined_by USING btree (person_id);
CREATE INDEX search_opinion_local_path_63290b39b28ef927_like ON public.search_opinion USING btree (local_path varchar_pattern_ops);
CREATE INDEX search_opinion_sha1_5887dd5d3475ad17_like ON public.search_opinion USING btree (sha1 varchar_pattern_ops);
CREATE INDEX search_opinioncluster_0b869b2f ON public.search_opinioncluster USING btree (date_blocked);
CREATE INDEX search_opinioncluster_1427d4ab ON public.search_opinioncluster USING btree (docket_id);
CREATE INDEX search_opinioncluster_5fdb3d66 ON public.search_opinioncluster USING btree (date_modified);
CREATE INDEX search_opinioncluster_61326117 ON public.search_opinioncluster USING btree (blocked);
CREATE INDEX search_opinioncluster_98cc5f59 ON public.search_opinioncluster USING btree (date_filed);
CREATE INDEX search_opinioncluster_c69e55a4 ON public.search_opinioncluster USING btree (date_created);
CREATE INDEX search_opinioncluster_d91c83eb ON public.search_opinioncluster USING btree (citation_count);
CREATE INDEX search_opinioncluster_e0fd3ccf ON public.search_opinioncluster USING btree (scdb_id);
CREATE INDEX search_opinioncluster_f796c05b ON public.search_opinioncluster USING btree (precedential_status);
CREATE INDEX search_opinioncluster_filepath_json_harvard_4b8057d0 ON public.search_opinioncluster USING btree (filepath_json_harvard);
CREATE INDEX search_opinioncluster_filepath_json_harvard_4b8057d0_like ON public.search_opinioncluster USING btree (filepath_json_harvard varchar_pattern_ops);
CREATE INDEX search_opinioncluster_non_participating_judges_49bb60ae ON public.search_opinioncluster_non_participating_judges USING btree (opinioncluster_id);
CREATE INDEX search_opinioncluster_non_participating_judges_e7c5d788 ON public.search_opinioncluster_non_participating_judges USING btree (person_id);
CREATE INDEX search_opinioncluster_panel_49bb60ae ON public.search_opinioncluster_panel USING btree (opinioncluster_id);
CREATE INDEX search_opinioncluster_panel_e7c5d788 ON public.search_opinioncluster_panel USING btree (person_id);
CREATE INDEX search_opinioncluster_precedential_status_2bdec6e2dedba28b_like ON public.search_opinioncluster USING btree (precedential_status varchar_pattern_ops);
CREATE INDEX search_opinioncluster_supreme_court_db_id_4297061ed6ba336_like ON public.search_opinioncluster USING btree (scdb_id varchar_pattern_ops);
CREATE INDEX search_opinionclusterevent_docket_id_165932da ON public.search_opinionclusterevent USING btree (docket_id);
CREATE INDEX search_opinionclusterevent_pgh_context_id_273003da ON public.search_opinionclusterevent USING btree (pgh_context_id);
CREATE INDEX search_opinionclusterevent_pgh_obj_id_f1ea380d ON public.search_opinionclusterevent USING btree (pgh_obj_id);
CREATE INDEX search_opinionclusternonpa_opinioncluster_id_cc505710 ON public.search_opinionclusternonparticipatingjudgesevent USING btree (opinioncluster_id);
CREATE INDEX search_opinionclusternonpa_person_id_7bf4f773 ON public.search_opinionclusternonparticipatingjudgesevent USING btree (person_id);
CREATE INDEX search_opinionclusternonpa_pgh_context_id_aef74bea ON public.search_opinionclusternonparticipatingjudgesevent USING btree (pgh_context_id);
CREATE INDEX search_opinionclusterpanelevent_opinioncluster_id_7128c9e4 ON public.search_opinionclusterpanelevent USING btree (opinioncluster_id);
CREATE INDEX search_opinionclusterpanelevent_person_id_b1c6a4a7 ON public.search_opinionclusterpanelevent USING btree (person_id);
CREATE INDEX search_opinionclusterpanelevent_pgh_context_id_8dcb8078 ON public.search_opinionclusterpanelevent USING btree (pgh_context_id);
CREATE INDEX search_opinionevent_author_id_43b0c67a ON public.search_opinionevent USING btree (author_id);
CREATE INDEX search_opinionevent_cluster_id_1205465b ON public.search_opinionevent USING btree (cluster_id);
CREATE INDEX search_opinionevent_pgh_context_id_723082e0 ON public.search_opinionevent USING btree (pgh_context_id);
CREATE INDEX search_opinionevent_pgh_obj_id_63a2bc5f ON public.search_opinionevent USING btree (pgh_obj_id);
CREATE INDEX search_opinionjoinedbyevent_opinion_id_9271b281 ON public.search_opinionjoinedbyevent USING btree (opinion_id);
CREATE INDEX search_opinionjoinedbyevent_person_id_dffa9dcb ON public.search_opinionjoinedbyevent USING btree (person_id);
CREATE INDEX search_opinionjoinedbyevent_pgh_context_id_48acc9ad ON public.search_opinionjoinedbyevent USING btree (pgh_context_id);
CREATE INDEX search_opinionscited_5b8b69a0 ON public.search_opinionscited USING btree (citing_opinion_id);
CREATE INDEX search_opinionscited_740050e6 ON public.search_opinionscited USING btree (cited_opinion_id);
CREATE INDEX search_opinionscited_depth_46bacaef ON public.search_opinionscited USING btree (depth);
CREATE INDEX search_opinionscitedbyrecapdocument_cited_opinion_id_5f0347bb ON public.search_opinionscitedbyrecapdocument USING btree (cited_opinion_id);
CREATE INDEX search_opinionscitedbyrecapdocument_citing_document_id_c64b751b ON public.search_opinionscitedbyrecapdocument USING btree (citing_document_id);
CREATE INDEX search_originatingcourtinf_ordering_judge_id_5aa931cb ON public.search_originatingcourtinformationevent USING btree (ordering_judge_id);
CREATE INDEX search_originatingcourtinformation_02c1725c ON public.search_originatingcourtinformation USING btree (assigned_to_id);
CREATE INDEX search_originatingcourtinformation_09a6c128 ON public.search_originatingcourtinformation USING btree (ordering_judge_id);
CREATE INDEX search_originatingcourtinformation_5fdb3d66 ON public.search_originatingcourtinformation USING btree (date_modified);
CREATE INDEX search_originatingcourtinformation_c69e55a4 ON public.search_originatingcourtinformation USING btree (date_created);
CREATE INDEX search_originatingcourtinformationevent_assigned_to_id_fcce9094 ON public.search_originatingcourtinformationevent USING btree (assigned_to_id);
CREATE INDEX search_originatingcourtinformationevent_pgh_context_id_d8ffc4c8 ON public.search_originatingcourtinformationevent USING btree (pgh_context_id);
CREATE INDEX search_originatingcourtinformationevent_pgh_obj_id_32490a9c ON public.search_originatingcourtinformationevent USING btree (pgh_obj_id);
CREATE INDEX search_pare_score_16f118_idx ON public.search_parentheticalgroup USING btree (score);
CREATE INDEX search_parenthetical_described_opinion_id_ddd408db ON public.search_parenthetical USING btree (described_opinion_id);
CREATE INDEX search_parenthetical_describing_opinion_id_07864494 ON public.search_parenthetical USING btree (describing_opinion_id);
CREATE INDEX search_parenthetical_group_id_00a7def3 ON public.search_parenthetical USING btree (group_id);
CREATE INDEX search_parenthetical_score_cab0b2a1 ON public.search_parenthetical USING btree (score);
CREATE INDEX search_parentheticalgroup_opinion_id_fd6bb935 ON public.search_parentheticalgroup USING btree (opinion_id);
CREATE INDEX search_parentheticalgroup_representative_id_00e5a857 ON public.search_parentheticalgroup USING btree (representative_id);
CREATE INDEX search_reca_documen_cc5acd_idx ON public.search_recapdocument USING btree (document_type, document_number, attachment_number);
CREATE INDEX search_recapdocument_1dec38a6 ON public.search_recapdocument USING btree (is_free_on_pacer);
CREATE INDEX search_recapdocument_40d913b2 ON public.search_recapdocument USING btree (docket_entry_id);
CREATE INDEX search_recapdocument_5fdb3d66 ON public.search_recapdocument USING btree (date_modified);
CREATE INDEX search_recapdocument_c69e55a4 ON public.search_recapdocument USING btree (date_created);
CREATE INDEX search_recapdocument_document_number_6f825e81ddd11fde_uniq ON public.search_recapdocument USING btree (document_number);
CREATE INDEX search_recapdocument_filepath_local_7dc6b0e53ccf753_uniq ON public.search_recapdocument USING btree (filepath_local);
CREATE INDEX search_recapdocument_pacer_doc_id_12ec9c122839e6aa_like ON public.search_recapdocument USING btree (pacer_doc_id varchar_pattern_ops);
CREATE INDEX search_recapdocument_tags_76f094bc ON public.search_recapdocument_tags USING btree (tag_id);
CREATE INDEX search_recapdocument_tags_fae26ff6 ON public.search_recapdocument_tags USING btree (recapdocument_id);
CREATE INDEX search_recapdocumentevent_docket_entry_id_055ee57b ON public.search_recapdocumentevent USING btree (docket_entry_id);
CREATE INDEX search_recapdocumentevent_pgh_context_id_37bf47c3 ON public.search_recapdocumentevent USING btree (pgh_context_id);
CREATE INDEX search_recapdocumentevent_pgh_obj_id_aa9c8d6e ON public.search_recapdocumentevent USING btree (pgh_obj_id);
CREATE INDEX search_recapdocumenttagsevent_pgh_context_id_ff9be284 ON public.search_recapdocumenttagsevent USING btree (pgh_context_id);
CREATE INDEX search_recapdocumenttagsevent_recapdocument_id_c6f0a858 ON public.search_recapdocumenttagsevent USING btree (recapdocument_id);
CREATE INDEX search_recapdocumenttagsevent_tag_id_9fa96f02 ON public.search_recapdocumenttagsevent USING btree (tag_id);
CREATE INDEX search_tag_5fdb3d66 ON public.search_tag USING btree (date_modified);CREATE INDEX search_tag_c69e55a4 ON public.search_tag USING btree (date_created);CREATE INDEX search_tag_name_30c16b352387258b_like ON public.search_tag USING btree (name varchar_pattern_ops);CREATE INDEX search_tagevent_pgh_context_id_03f699de ON public.search_tagevent USING btree (pgh_context_id);CREATE INDEX search_tagevent_pgh_obj_id_af8c9817 ON public.search_tagevent USING btree (pgh_obj_id);
