--
-- Name: courtlistener; Type: DATABASE; Schema: -; Owner: david
--

CREATE DATABASE courtlistener WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'en_US.UTF-8';
ALTER DATABASE courtlistener OWNER TO david;

\connect courtlistener

------------------------------------------------------------------------------------
------------------------------------------------------------------------------------
--
-- Name: search_court; Type: TABLE; Schema: public; Owner: david
--
CREATE TABLE public.search_court (
    id character varying(15) NOT NULL,
    date_modified timestamp with time zone NOT NULL,
    in_use boolean NOT NULL,
    has_opinion_scraper boolean NOT NULL,
    has_oral_argument_scraper boolean NOT NULL,
    "position" double precision NOT NULL,
    citation_string character varying(100) NOT NULL,
    short_name character varying(100) NOT NULL,
    full_name character varying(200) NOT NULL,
    url character varying(500) NOT NULL,
    start_date date,
    end_date date,
    jurisdiction character varying(3) NOT NULL,
    notes text NOT NULL,
    pacer_court_id smallint,
    fjc_court_id character varying(3) NOT NULL,
    pacer_has_rss_feed boolean,
    date_last_pacer_contact timestamp with time zone,
    pacer_rss_entry_types text NOT NULL,
    parent_court_id character varying(15),
    CONSTRAINT search_court_pacer_court_id_check CHECK ((pacer_court_id >= 0))
);
ALTER TABLE public.search_court OWNER TO david;
-- echo "Loading courts-2023-12-04.csv to database"
COPY public.search_court ( id, pacer_court_id, pacer_has_rss_feed,
     pacer_rss_entry_types, date_last_pacer_contact, fjc_court_id,
     date_modified, in_use, has_opinion_scraper,
     has_oral_argument_scraper, position, citation_string, short_name,
     full_name, url, start_date, end_date, jurisdiction, notes,
     parent_court_id ) FROM
     '/Volumes/aspen_cove/data/courtlistener/courts-2023-12-04.csv'
     WITH (FORMAT csv, ENCODING utf8, HEADER);

------------------------------------------------------------------------------------
--
-- Name: search_courthouse; Type: TABLE; Schema: public; Owner: david
--
CREATE TABLE public.search_courthouse (
    id integer NOT NULL,
    court_seat boolean,
    building_name text NOT NULL,
    address1 text NOT NULL,
    address2 text NOT NULL,
    city text NOT NULL,
    county text NOT NULL,
    state character varying(2) NOT NULL,
    zip_code character varying(10) NOT NULL,
    country_code text NOT NULL,
    court_id character varying(15) NOT NULL
);
ALTER TABLE public.search_courthouse OWNER TO david;
-- echo "Loading courthouses-2023-12-04.csv to database"

COPY public.search_courthouse (id, court_seat, building_name,
     address1, address2, city, county, state, zip_code, country_code,
     court_id) FROM
     '/Volumes/aspen_cove/data/courtlistener/courthouses-2023-12-04.csv'
     WITH (FORMAT csv, ENCODING utf8, HEADER);

--
-- Name: search_courthouse_id_seq; Type: SEQUENCE; Schema: public; Owner: david
--
ALTER TABLE public.search_courthouse ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.search_courthouse_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
--
-- Name: search_courthouseevent; Type: TABLE; Schema: public; Owner: david
--
CREATE TABLE public.search_courthouseevent (
    pgh_id integer NOT NULL,
    pgh_created_at timestamp with time zone NOT NULL,
    pgh_label text NOT NULL,
    id integer NOT NULL,
    court_seat boolean,
    building_name text NOT NULL,
    address1 text NOT NULL,
    address2 text NOT NULL,
    city text NOT NULL,
    county text NOT NULL,
    state character varying(2) NOT NULL,
    zip_code character varying(10) NOT NULL,
    country_code text NOT NULL,
    court_id character varying(15) NOT NULL,
    pgh_context_id uuid,
    pgh_obj_id integer NOT NULL
);
ALTER TABLE public.search_courthouseevent OWNER TO david;
--
-- Name: search_courthouseevent_pgh_id_seq; Type: SEQUENCE; Schema: public; Owner: david
--
ALTER TABLE public.search_courthouseevent ALTER COLUMN pgh_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.search_courthouseevent_pgh_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

------------------------------------------------------------------------------------
--
-- Name: search_court_appeals_to; Type: TABLE; Schema: public; Owner: david
--
CREATE TABLE public.search_court_appeals_to (
    id integer NOT NULL,
    from_court_id character varying(15) NOT NULL,
    to_court_id character varying(15) NOT NULL
);
ALTER TABLE public.search_court_appeals_to OWNER TO david;

-- echo "Loading court-appeals-to-2023-12-04.csv to database"
COPY public.search_court_appeals_to (id, from_court_id, to_court_id)
FROM '/Volumes/aspen_cove/data/courtlistener/court-appeals-to-2023-12-04.csv' WITH (FORMAT csv, ENCODING utf8, HEADER);

------------------------------------------------------------------------------------
--
-- Name: search_docket; Type: TABLE; Schema: public; Owner: david
--
CREATE TABLE public.search_docket (
    id integer NOT NULL,
    date_created timestamp with time zone NOT NULL,
    date_modified timestamp with time zone NOT NULL,
    date_argued date,
    date_reargued date,
    date_reargument_denied date,
    case_name_short text NOT NULL,
    case_name text NOT NULL,
    case_name_full text NOT NULL,
    slug character varying(75) NOT NULL,
    docket_number text,
    date_blocked date,
    blocked boolean NOT NULL,
    court_id character varying(15) NOT NULL,
    date_cert_denied date,
    date_cert_granted date,
    assigned_to_id integer,
    cause character varying(2000) NOT NULL,
    date_filed date,
    date_last_filing date,
    date_terminated date,
    filepath_ia character varying(1000) NOT NULL,
    filepath_local character varying(1000) NOT NULL,
    jurisdiction_type character varying(100) NOT NULL,
    jury_demand character varying(500) NOT NULL,
    nature_of_suit character varying(1000) NOT NULL,
    pacer_case_id character varying(100),
    referred_to_id integer,
    source smallint NOT NULL,
    assigned_to_str text NOT NULL,
    referred_to_str text NOT NULL,
    view_count integer NOT NULL,
    date_last_index timestamp with time zone,
    appeal_from_id character varying(15),
    appeal_from_str text NOT NULL,
    appellate_case_type_information text NOT NULL,
    appellate_fee_status text NOT NULL,
    panel_str text NOT NULL,
    originating_court_information_id integer,
    mdl_status character varying(100) NOT NULL,
    filepath_ia_json character varying(1000) NOT NULL,
    ia_date_first_change timestamp with time zone,
    ia_needs_upload boolean,
    ia_upload_failure_count smallint,
    docket_number_core character varying(20) NOT NULL,
    idb_data_id integer
);
ALTER TABLE public.search_docket OWNER TO david;
-- echo "Loading dockets-2023-12-04.csv to database"

COPY public.search_docket (id, date_created, date_modified, source,
	       appeal_from_str, assigned_to_str, referred_to_str,
	       panel_str, date_last_index, date_cert_granted,
	       date_cert_denied, date_argued, date_reargued,
	       date_reargument_denied, date_filed, date_terminated,
	       date_last_filing, case_name_short, case_name,
	       case_name_full, slug, docket_number,
	       docket_number_core, pacer_case_id, cause,
	       nature_of_suit, jury_demand, jurisdiction_type,
	       appellate_fee_status, appellate_case_type_information,
	       mdl_status, filepath_local, filepath_ia,
	       filepath_ia_json, ia_upload_failure_count,
	       ia_needs_upload, ia_date_first_change, view_count,
	       date_blocked, blocked, appeal_from_id, assigned_to_id,
	       court_id, idb_data_id,
	       originating_court_information_id, referred_to_id ) FROM
	       '/Volumes/aspen_cove/data/courtlistener/dockets-2023-12-04.csv'
	       WITH (FORMAT csv, ENCODING utf8, HEADER);

--
-- Name: search_docket_id_seq; Type: SEQUENCE; Schema: public; Owner: david
--
CREATE SEQUENCE public.search_docket_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.search_docket_id_seq OWNER TO david;

--
-- Name: search_docket_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: david
--
ALTER SEQUENCE public.search_docket_id_seq OWNED BY public.search_docket.id;

--
-- Name: search_docket_panel; Type: TABLE; Schema: public; Owner: david
--
CREATE TABLE public.search_docket_panel (
    id integer NOT NULL,
    docket_id integer NOT NULL,
    person_id integer NOT NULL
);
ALTER TABLE public.search_docket_panel OWNER TO david;

--
-- Name: search_docket_panel_id_seq; Type: SEQUENCE; Schema: public; Owner: david
--
CREATE SEQUENCE public.search_docket_panel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.search_docket_panel_id_seq OWNER TO david;

--
-- Name: search_docket_panel_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: david
--
ALTER SEQUENCE public.search_docket_panel_id_seq OWNED BY public.search_docket_panel.id;

--
-- Name: search_docket_tags; Type: TABLE; Schema: public; Owner: david
--

CREATE TABLE public.search_docket_tags (
    id integer NOT NULL,
    docket_id integer NOT NULL,
    tag_id integer NOT NULL
);
ALTER TABLE public.search_docket_tags OWNER TO david;


--
-- Name: search_docket_tags_id_seq; Type: SEQUENCE; Schema: public; Owner: david
--
CREATE SEQUENCE public.search_docket_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.search_docket_tags_id_seq OWNER TO david;

--
-- Name: search_docket_tags_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: david
--
ALTER SEQUENCE public.search_docket_tags_id_seq OWNED BY public.search_docket_tags.id;

--
-- Name: search_docketentry; Type: TABLE; Schema: public; Owner: david
--
CREATE TABLE public.search_docketentry (
    id integer NOT NULL,
    date_created timestamp with time zone NOT NULL,
    date_modified timestamp with time zone NOT NULL,
    date_filed date,
    entry_number bigint,
    description text NOT NULL,
    docket_id integer NOT NULL,
    pacer_sequence_number integer,
    recap_sequence_number character varying(50) NOT NULL,
    time_filed time without time zone
);

ALTER TABLE public.search_docketentry OWNER TO david;

--
-- Name: search_docketentry_id_seq; Type: SEQUENCE; Schema: public; Owner: david
--

CREATE SEQUENCE public.search_docketentry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.search_docketentry_id_seq OWNER TO david;

--
-- Name: search_docketentry_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: david
--
ALTER SEQUENCE public.search_docketentry_id_seq OWNED BY public.search_docketentry.id;


--
-- Name: search_docketentry_tags; Type: TABLE; Schema: public; Owner: david
--

CREATE TABLE public.search_docketentry_tags (
    id integer NOT NULL,
    docketentry_id integer NOT NULL,
    tag_id integer NOT NULL
);

ALTER TABLE public.search_docketentry_tags OWNER TO david;

--
-- Name: search_docketentry_tags_id_seq; Type: SEQUENCE; Schema: public; Owner: david
--

CREATE SEQUENCE public.search_docketentry_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.search_docketentry_tags_id_seq OWNER TO david;

--
-- Name: search_docketentry_tags_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: david
--
ALTER SEQUENCE public.search_docketentry_tags_id_seq OWNED BY public.search_docketentry_tags.id;


--
-- Name: search_docketentryevent; Type: TABLE; Schema: public; Owner: david
--

CREATE TABLE public.search_docketentryevent (
    pgh_id integer NOT NULL,
    pgh_created_at timestamp with time zone NOT NULL,
    pgh_label text NOT NULL,
    id integer NOT NULL,
    date_created timestamp with time zone NOT NULL,
    date_modified timestamp with time zone NOT NULL,
    date_filed date,
    entry_number bigint,
    recap_sequence_number character varying(50) NOT NULL,
    pacer_sequence_number integer,
    description text NOT NULL,
    docket_id integer NOT NULL,
    pgh_context_id uuid,
    pgh_obj_id integer NOT NULL,
    time_filed time without time zone
);

ALTER TABLE public.search_docketentryevent OWNER TO david;

--
-- Name: search_docketentryevent_pgh_id_seq; Type: SEQUENCE; Schema: public; Owner: david
--

CREATE SEQUENCE public.search_docketentryevent_pgh_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.search_docketentryevent_pgh_id_seq OWNER TO david;

--
-- Name: search_docketentryevent_pgh_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: david
--
ALTER SEQUENCE public.search_docketentryevent_pgh_id_seq OWNED BY public.search_docketentryevent.pgh_id;


--
-- Name: search_docketentrytagsevent; Type: TABLE; Schema: public; Owner: david
--

CREATE TABLE public.search_docketentrytagsevent (
    pgh_id integer NOT NULL,
    pgh_created_at timestamp with time zone NOT NULL,
    pgh_label text NOT NULL,
    id integer NOT NULL,
    docketentry_id integer NOT NULL,
    pgh_context_id uuid,
    tag_id integer NOT NULL
);

ALTER TABLE public.search_docketentrytagsevent OWNER TO david;

--
-- Name: search_docketentrytagsevent_pgh_id_seq; Type: SEQUENCE; Schema: public; Owner: david
--

CREATE SEQUENCE public.search_docketentrytagsevent_pgh_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.search_docketentrytagsevent_pgh_id_seq OWNER TO david;

--
-- Name: search_docketentrytagsevent_pgh_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: david
--
ALTER SEQUENCE public.search_docketentrytagsevent_pgh_id_seq OWNED BY public.search_docketentrytagsevent.pgh_id;


--
-- Name: search_docketevent; Type: TABLE; Schema: public; Owner: david
--

CREATE TABLE public.search_docketevent (
    pgh_id integer NOT NULL,
    pgh_created_at timestamp with time zone NOT NULL,
    pgh_label text NOT NULL,
    id integer NOT NULL,
    date_created timestamp with time zone NOT NULL,
    date_modified timestamp with time zone NOT NULL,
    source smallint NOT NULL,
    appeal_from_str text NOT NULL,
    assigned_to_str text NOT NULL,
    referred_to_str text NOT NULL,
    panel_str text NOT NULL,
    date_last_index timestamp with time zone,
    date_cert_granted date,
    date_cert_denied date,
    date_argued date,
    date_reargued date,
    date_reargument_denied date,
    date_filed date,
    date_terminated date,
    date_last_filing date,
    case_name_short text NOT NULL,
    case_name text NOT NULL,
    case_name_full text NOT NULL,
    slug character varying(75) NOT NULL,
    docket_number text,
    docket_number_core character varying(20) NOT NULL,
    pacer_case_id character varying(100),
    cause character varying(2000) NOT NULL,
    nature_of_suit character varying(1000) NOT NULL,
    jury_demand character varying(500) NOT NULL,
    jurisdiction_type character varying(100) NOT NULL,
    appellate_fee_status text NOT NULL,
    appellate_case_type_information text NOT NULL,
    mdl_status character varying(100) NOT NULL,
    filepath_local character varying(1000) NOT NULL,
    filepath_ia character varying(1000) NOT NULL,
    filepath_ia_json character varying(1000) NOT NULL,
    ia_upload_failure_count smallint,
    ia_needs_upload boolean,
    ia_date_first_change timestamp with time zone,
    date_blocked date,
    blocked boolean NOT NULL,
    appeal_from_id character varying(15),
    assigned_to_id integer,
    court_id character varying(15) NOT NULL,
    idb_data_id integer,
    originating_court_information_id integer,
    pgh_context_id uuid,
    pgh_obj_id integer NOT NULL,
    referred_to_id integer
);

ALTER TABLE public.search_docketevent OWNER TO david;

--
-- Name: search_docketevent_pgh_id_seq; Type: SEQUENCE; Schema: public; Owner: david
--

CREATE SEQUENCE public.search_docketevent_pgh_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.search_docketevent_pgh_id_seq OWNER TO david;
--
-- Name: search_docketevent_pgh_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: david
--
ALTER SEQUENCE public.search_docketevent_pgh_id_seq OWNED BY public.search_docketevent.pgh_id;
--
-- Name: search_docketpanelevent; Type: TABLE; Schema: public; Owner: david
--
CREATE TABLE public.search_docketpanelevent (
    pgh_id integer NOT NULL,
    pgh_created_at timestamp with time zone NOT NULL,
    pgh_label text NOT NULL,
    id integer NOT NULL,
    docket_id integer NOT NULL,
    person_id integer NOT NULL,
    pgh_context_id uuid
);
ALTER TABLE public.search_docketpanelevent OWNER TO david;
--
-- Name: search_docketpanelevent_pgh_id_seq; Type: SEQUENCE; Schema: public; Owner: david
--
CREATE SEQUENCE public.search_docketpanelevent_pgh_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.search_docketpanelevent_pgh_id_seq OWNER TO david;
--
-- Name: search_docketpanelevent_pgh_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: david
--
ALTER SEQUENCE public.search_docketpanelevent_pgh_id_seq OWNED BY public.search_docketpanelevent.pgh_id;
--
-- Name: search_dockettagsevent; Type: TABLE; Schema: public; Owner: david
--
CREATE TABLE public.search_dockettagsevent (
    pgh_id integer NOT NULL,
    pgh_created_at timestamp with time zone NOT NULL,
    pgh_label text NOT NULL,
    id integer NOT NULL,
    docket_id integer NOT NULL,
    pgh_context_id uuid,
    tag_id integer NOT NULL
);

ALTER TABLE public.search_dockettagsevent OWNER TO david;

--
-- Name: search_dockettagsevent_pgh_id_seq; Type: SEQUENCE; Schema: public; Owner: david
--

CREATE SEQUENCE public.search_dockettagsevent_pgh_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.search_dockettagsevent_pgh_id_seq OWNER TO david;
--
-- Name: search_dockettagsevent_pgh_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: david
--
ALTER SEQUENCE public.search_dockettagsevent_pgh_id_seq OWNED BY public.search_dockettagsevent.pgh_id;

------------------------------------------------------------------------------------
--
-- Name: search_originatingcourtinformation; Type: TABLE; Schema: public; Owner: david
--
CREATE TABLE public.search_originatingcourtinformation (
    id integer NOT NULL,
    date_created timestamp with time zone NOT NULL,
    date_modified timestamp with time zone NOT NULL,
    assigned_to_str text NOT NULL,
    court_reporter text NOT NULL,
    date_disposed date,
    date_filed date,
    date_judgment date,
    date_judgment_eod date,
    date_filed_noa date,
    date_received_coa date,
    assigned_to_id integer,
    docket_number text NOT NULL,
    ordering_judge_id integer,
    ordering_judge_str text NOT NULL
);
ALTER TABLE public.search_originatingcourtinformation OWNER TO david;

-- echo "Loading originating-court-information-2023-12-04.csv to database"
COPY public.search_originatingcourtinformation (
	       id, date_created, date_modified, docket_number, assigned_to_str,
	       ordering_judge_str, court_reporter, date_disposed, date_filed, date_judgment,
	       date_judgment_eod, date_filed_noa, date_received_coa, assigned_to_id,
	       ordering_judge_id
	       ) FROM '/Volumes/aspen_cove/data/courtlistener/originating-court-information-2023-12-04.csv' WITH (FORMAT csv, ENCODING utf8, HEADER);

------------------------------------------------------------------------------------
--
-- Name: search_opinioncluster; Type: TABLE; Schema: public; Owner: david
--
CREATE TABLE public.search_opinioncluster (
    id integer NOT NULL,
    judges text NOT NULL,
    date_created timestamp with time zone NOT NULL,
    date_modified timestamp with time zone NOT NULL,
    date_filed date NOT NULL,
    slug character varying(75),
    case_name_short text NOT NULL,
    case_name text NOT NULL,
    case_name_full text NOT NULL,
    scdb_id character varying(10) NOT NULL,
    source character varying(10) NOT NULL,
    procedural_history text NOT NULL,
    attorneys text NOT NULL,
    nature_of_suit text NOT NULL,
    posture text NOT NULL,
    syllabus text NOT NULL,
    citation_count integer NOT NULL,
    precedential_status character varying(50) NOT NULL,
    date_blocked date,
    blocked boolean NOT NULL,
    docket_id integer NOT NULL,
    scdb_decision_direction integer,
    scdb_votes_majority integer,
    scdb_votes_minority integer,
    date_filed_is_approximate boolean NOT NULL,
    correction text NOT NULL,
    cross_reference text NOT NULL,
    disposition text NOT NULL,
    filepath_json_harvard character varying(1000) NOT NULL,
    headnotes text NOT NULL,
    history text NOT NULL,
    other_dates text NOT NULL,
    summary text NOT NULL,
    arguments text NOT NULL,
    headmatter text NOT NULL
);
ALTER TABLE public.search_opinioncluster OWNER TO david;

-- echo "Loading opinion-clusters-2023-12-04.csv to database"
COPY public.search_opinioncluster (
	       id, date_created, date_modified, judges, date_filed,
	       date_filed_is_approximate, slug, case_name_short, case_name,
	       case_name_full, scdb_id, scdb_decision_direction, scdb_votes_majority,
	       scdb_votes_minority, source, procedural_history, attorneys,
	       nature_of_suit, posture, syllabus, headnotes, summary, disposition,
	       history, other_dates, cross_reference, correction, citation_count,
	       precedential_status, date_blocked, blocked, filepath_json_harvard, docket_id,
	       arguments, headmatter
	   ) FROM '/Volumes/aspen_cove/data/courtlistener/opinion-clusters-2023-12-04.csv' WITH (FORMAT csv, ENCODING utf8, HEADER);

--
-- Name: search_opinioncluster_id_seq; Type: SEQUENCE; Schema: public; Owner: david
--

CREATE SEQUENCE public.search_opinioncluster_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.search_opinioncluster_id_seq OWNER TO david;

--
-- Name: search_opinioncluster_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: david
--
ALTER SEQUENCE public.search_opinioncluster_id_seq OWNED BY public.search_opinioncluster.id;

--
-- Name: search_opinioncluster_non_participating_judges; Type: TABLE; Schema: public; Owner: david
--

CREATE TABLE public.search_opinioncluster_non_participating_judges (
    id integer NOT NULL,
    opinioncluster_id integer NOT NULL,
    person_id integer NOT NULL
);

ALTER TABLE public.search_opinioncluster_non_participating_judges OWNER TO david;

--
-- Name: search_opinioncluster_non_participating_judges_id_seq; Type: SEQUENCE; Schema: public; Owner: david
--

CREATE SEQUENCE public.search_opinioncluster_non_participating_judges_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.search_opinioncluster_non_participating_judges_id_seq OWNER TO david;

--
-- Name: search_opinioncluster_non_participating_judges_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: david
--
ALTER SEQUENCE public.search_opinioncluster_non_participating_judges_id_seq OWNED BY public.search_opinioncluster_non_participating_judges.id;


--
-- Name: search_opinioncluster_panel; Type: TABLE; Schema: public; Owner: david
--

CREATE TABLE public.search_opinioncluster_panel (
    id integer NOT NULL,
    opinioncluster_id integer NOT NULL,
    person_id integer NOT NULL
);
ALTER TABLE public.search_opinioncluster_panel OWNER TO david;

--
-- Name: search_opinioncluster_panel_id_seq; Type: SEQUENCE; Schema: public; Owner: david
--

CREATE SEQUENCE public.search_opinioncluster_panel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.search_opinioncluster_panel_id_seq OWNER TO david;
--
-- Name: search_opinioncluster_panel_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: david
--
ALTER SEQUENCE public.search_opinioncluster_panel_id_seq OWNED BY public.search_opinioncluster_panel.id;
--
-- Name: search_opinionclusterevent; Type: TABLE; Schema: public; Owner: david
--
CREATE TABLE public.search_opinionclusterevent (
    pgh_id integer NOT NULL,
    pgh_created_at timestamp with time zone NOT NULL,
    pgh_label text NOT NULL,
    id integer NOT NULL,
    date_created timestamp with time zone NOT NULL,
    date_modified timestamp with time zone NOT NULL,
    judges text NOT NULL,
    date_filed date NOT NULL,
    date_filed_is_approximate boolean NOT NULL,
    slug character varying(75),
    case_name_short text NOT NULL,
    case_name text NOT NULL,
    case_name_full text NOT NULL,
    scdb_id character varying(10) NOT NULL,
    scdb_decision_direction integer,
    scdb_votes_majority integer,
    scdb_votes_minority integer,
    source character varying(10) NOT NULL,
    procedural_history text NOT NULL,
    attorneys text NOT NULL,
    nature_of_suit text NOT NULL,
    posture text NOT NULL,
    syllabus text NOT NULL,
    headnotes text NOT NULL,
    summary text NOT NULL,
    disposition text NOT NULL,
    history text NOT NULL,
    other_dates text NOT NULL,
    cross_reference text NOT NULL,
    correction text NOT NULL,
    citation_count integer NOT NULL,
    precedential_status character varying(50) NOT NULL,
    date_blocked date,
    blocked boolean NOT NULL,
    filepath_json_harvard character varying(1000) NOT NULL,
    docket_id integer NOT NULL,
    pgh_context_id uuid,
    pgh_obj_id integer NOT NULL,
    arguments text NOT NULL,
    headmatter text NOT NULL
);

ALTER TABLE public.search_opinionclusterevent OWNER TO david;

--
-- Name: search_opinionclusterevent_pgh_id_seq; Type: SEQUENCE; Schema: public; Owner: david
--

CREATE SEQUENCE public.search_opinionclusterevent_pgh_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.search_opinionclusterevent_pgh_id_seq OWNER TO david;

--
-- Name: search_opinionclusterevent_pgh_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: david
--
ALTER SEQUENCE public.search_opinionclusterevent_pgh_id_seq OWNED BY public.search_opinionclusterevent.pgh_id;


--
-- Name: search_opinionclusternonparticipatingjudgesevent; Type: TABLE; Schema: public; Owner: david
--

CREATE TABLE public.search_opinionclusternonparticipatingjudgesevent (
    pgh_id integer NOT NULL,
    pgh_created_at timestamp with time zone NOT NULL,
    pgh_label text NOT NULL,
    id integer NOT NULL,
    opinioncluster_id integer NOT NULL,
    person_id integer NOT NULL,
    pgh_context_id uuid
);

ALTER TABLE public.search_opinionclusternonparticipatingjudgesevent OWNER TO david;

--
-- Name: search_opinionclusternonparticipatingjudgesevent_pgh_id_seq; Type: SEQUENCE; Schema: public; Owner: david
--

CREATE SEQUENCE public.search_opinionclusternonparticipatingjudgesevent_pgh_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.search_opinionclusternonparticipatingjudgesevent_pgh_id_seq OWNER TO david;

--
-- Name: search_opinionclusternonparticipatingjudgesevent_pgh_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: david
--
ALTER SEQUENCE public.search_opinionclusternonparticipatingjudgesevent_pgh_id_seq OWNED BY public.search_opinionclusternonparticipatingjudgesevent.pgh_id;


--
-- Name: search_opinionclusterpanelevent; Type: TABLE; Schema: public; Owner: david
--

CREATE TABLE public.search_opinionclusterpanelevent (
    pgh_id integer NOT NULL,
    pgh_created_at timestamp with time zone NOT NULL,
    pgh_label text NOT NULL,
    id integer NOT NULL,
    opinioncluster_id integer NOT NULL,
    person_id integer NOT NULL,
    pgh_context_id uuid
);

ALTER TABLE public.search_opinionclusterpanelevent OWNER TO david;

--
-- Name: search_opinionclusterpanelevent_pgh_id_seq; Type: SEQUENCE; Schema: public; Owner: david
--

CREATE SEQUENCE public.search_opinionclusterpanelevent_pgh_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.search_opinionclusterpanelevent_pgh_id_seq OWNER TO david;

--
-- Name: search_opinionclusterpanelevent_pgh_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: david
--
ALTER SEQUENCE public.search_opinionclusterpanelevent_pgh_id_seq OWNED BY public.search_opinionclusterpanelevent.pgh_id;

------------------------------------------------------------------------------------
--
-- Name: search_opinion; Type: TABLE; Schema: public; Owner: david
--
CREATE TABLE public.search_opinion (
    id integer NOT NULL,
    date_created timestamp with time zone NOT NULL,
    date_modified timestamp with time zone NOT NULL,
    type character varying(20) NOT NULL,
    sha1 character varying(40) NOT NULL,
    download_url character varying(500),
    local_path character varying(100) NOT NULL,
    plain_text text NOT NULL,
    html text NOT NULL,
    html_lawbox text NOT NULL,
    html_columbia text NOT NULL,
    html_with_citations text NOT NULL,
    extracted_by_ocr boolean NOT NULL,
    author_id integer,
    cluster_id integer NOT NULL,
    per_curiam boolean NOT NULL,
    page_count integer,
    author_str text NOT NULL,
    joined_by_str text NOT NULL,
    xml_harvard text NOT NULL,
    html_anon_2020 text NOT NULL
);
ALTER TABLE public.search_opinion OWNER TO david;

-- echo "Loading opinions-2023-12-04.csv to database"
COPY public.search_opinion (
	       id, date_created, date_modified, author_str, per_curiam, joined_by_str,
	       type, sha1, page_count, download_url, local_path, plain_text, html,
	       html_lawbox, html_columbia, html_anon_2020, xml_harvard,
	       html_with_citations, extracted_by_ocr, author_id, cluster_id
	   ) FROM '/Volumes/aspen_cove/data/courtlistener/opinions-2023-12-04.csv' WITH (FORMAT csv, ENCODING utf8, HEADER);

--
-- Name: search_opinion_id_seq; Type: SEQUENCE; Schema: public; Owner: david
--

CREATE SEQUENCE public.search_opinion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.search_opinion_id_seq OWNER TO david;

--
-- Name: search_opinion_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: david
--
ALTER SEQUENCE public.search_opinion_id_seq OWNED BY public.search_opinion.id;


--
-- Name: search_opinion_joined_by; Type: TABLE; Schema: public; Owner: david
--

CREATE TABLE public.search_opinion_joined_by (
    id integer NOT NULL,
    opinion_id integer NOT NULL,
    person_id integer NOT NULL
);

ALTER TABLE public.search_opinion_joined_by OWNER TO david;

--
-- Name: search_opinion_joined_by_id_seq; Type: SEQUENCE; Schema: public; Owner: david
--

CREATE SEQUENCE public.search_opinion_joined_by_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.search_opinion_joined_by_id_seq OWNER TO david;

--
-- Name: search_opinion_joined_by_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: david
--
ALTER SEQUENCE public.search_opinion_joined_by_id_seq OWNED BY public.search_opinion_joined_by.id;


------------------------------------------------------------------------------------
--
-- Name: search_opinionscited; Type: TABLE; Schema: public; Owner: david
--

CREATE TABLE public.search_opinionscited (
    id integer NOT NULL,
    cited_opinion_id integer NOT NULL,
    citing_opinion_id integer NOT NULL,
    depth integer NOT NULL
);
ALTER TABLE public.search_opinionscited OWNER TO david;

-- echo "Loading citation-map-2023-12-04.csv to database"
COPY public.search_opinionscited (
	       id, depth, cited_opinion_id, citing_opinion_id
	   ) FROM '/Volumes/aspen_cove/data/courtlistener/citation-map-2023-12-04.csv' WITH (FORMAT csv, ENCODING utf8, HEADER);

------------------------------------------------------------------------------------
--
-- Name: search_citation; Type: TABLE; Schema: public; Owner: david
--
CREATE TABLE public.search_citation (
    id integer NOT NULL,
    volume smallint NOT NULL,
    reporter text NOT NULL,
    page text NOT NULL,
    type smallint NOT NULL,
    cluster_id integer NOT NULL
);
ALTER TABLE public.search_citation OWNER TO david;

-- echo "Loading citations-2023-12-04.csv to database"
COPY public.search_citation (
	       id, volume, reporter, page, type, cluster_id
	   ) FROM '/Volumes/aspen_cove/data/courtlistener/citations-2023-12-04.csv' WITH (FORMAT csv, ENCODING utf8, HEADER);

------------------------------------------------------------------------------------
--
-- Name: search_parenthetical; Type: TABLE; Schema: public; Owner: david
--
CREATE TABLE public.search_parenthetical (
    id integer NOT NULL,
    text text NOT NULL,
    score double precision NOT NULL,
    described_opinion_id integer NOT NULL,
    describing_opinion_id integer NOT NULL,
    group_id integer
);
ALTER TABLE public.search_parenthetical OWNER TO david;

-- echo "Loading parentheticals-2023-12-04.csv to database"
COPY public.search_parenthetical (
	       id, text, score, described_opinion_id, describing_opinion_id, group_id
	   ) FROM '/Volumes/aspen_cove/data/courtlistener/parentheticals-2023-12-04.csv' WITH (FORMAT csv, ENCODING utf8, HEADER);

------------------------------------------------------------------------------------
--
-- Name: audio_audio; Type: TABLE; Schema: public; Owner: david
--
CREATE TABLE public.audio_audio (
    id integer NOT NULL,
    source character varying(10) NOT NULL,
    case_name_short text NOT NULL,
    case_name text NOT NULL,
    case_name_full text NOT NULL,
    judges text,
    date_created timestamp with time zone NOT NULL,
    date_modified timestamp with time zone NOT NULL,
    sha1 character varying(40) NOT NULL,
    download_url character varying(500),
    local_path_mp3 character varying(100) NOT NULL,
    local_path_original_file character varying(100) NOT NULL,
    duration smallint,
    processing_complete boolean NOT NULL,
    date_blocked date,
    blocked boolean NOT NULL,
    docket_id integer,
    stt_google_response text NOT NULL,
    stt_status smallint NOT NULL,
    filepath_ia character varying(1000) NOT NULL,
    ia_upload_failure_count smallint
);
ALTER TABLE public.audio_audio OWNER TO david;

-- echo "Loading oral-arguments-2023-12-04.csv to database"
COPY public.audio_audio (
	       id, date_created, date_modified, source, case_name_short,
	       case_name, case_name_full, judges, sha1, download_url, local_path_mp3,
	       local_path_original_file, filepath_ia, ia_upload_failure_count, duration,
	       processing_complete, date_blocked, blocked, stt_status, stt_google_response,
	       docket_id
	   ) FROM '/Volumes/aspen_cove/data/courtlistener/oral-arguments-2023-12-04.csv' WITH (FORMAT csv, ENCODING utf8, HEADER);



------------------------------------------------------------------------------------
--
-- Name: people_db_person; Type: TABLE; Schema: public; Owner: david
--

CREATE TABLE public.people_db_person (
    id integer NOT NULL,
    date_created timestamp with time zone NOT NULL,
    date_modified timestamp with time zone NOT NULL,
    fjc_id integer,
    slug character varying(158) NOT NULL,
    name_first character varying(50) NOT NULL,
    name_middle character varying(50) NOT NULL,
    name_last character varying(50) NOT NULL,
    name_suffix character varying(5) NOT NULL,
    date_dob date,
    date_granularity_dob character varying(15) NOT NULL,
    date_dod date,
    date_granularity_dod character varying(15) NOT NULL,
    dob_city character varying(50) NOT NULL,
    dob_state character varying(2) NOT NULL,
    dod_city character varying(50) NOT NULL,
    dod_state character varying(2) NOT NULL,
    gender character varying(2) NOT NULL,
    is_alias_of_id integer,
    religion character varying(30) NOT NULL,
    has_photo boolean NOT NULL,
    ftm_total_received double precision,
    ftm_eid character varying(30),
    date_completed timestamp with time zone,
    dob_country character varying(50) NOT NULL,
    dod_country character varying(50) NOT NULL
);
ALTER TABLE public.people_db_person OWNER TO david;

-- echo "Loading people-db-people-2023-12-04.csv to database"
COPY public.people_db_person (
	       id, date_created, date_modified, date_completed, fjc_id, slug, name_first,
	       name_middle, name_last, name_suffix, date_dob, date_granularity_dob,
	       date_dod, date_granularity_dod, dob_city, dob_state, dob_country,
	       dod_city, dod_state, dod_country, gender, religion, ftm_total_received,
	       ftm_eid, has_photo, is_alias_of_id
	   ) FROM '/Volumes/aspen_cove/data/courtlistener/people-db-people-2023-12-04.csv' WITH (FORMAT csv, ENCODING utf8, HEADER);

--
-- Name: people_db_person_id_seq; Type: SEQUENCE; Schema: public; Owner: david
--
CREATE SEQUENCE public.people_db_person_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.people_db_person_id_seq OWNER TO david;
--
-- Name: people_db_person_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: david
--
ALTER SEQUENCE public.people_db_person_id_seq OWNED BY public.people_db_person.id;
--
-- Name: people_db_person_race; Type: TABLE; Schema: public; Owner: david
--
CREATE TABLE public.people_db_person_race (
    id integer NOT NULL,
    person_id integer NOT NULL,
    race_id integer NOT NULL
);
ALTER TABLE public.people_db_person_race OWNER TO david;
--
-- Name: people_db_person_race_id_seq; Type: SEQUENCE; Schema: public; Owner: david
--
CREATE SEQUENCE public.people_db_person_race_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.people_db_person_race_id_seq OWNER TO david;
--
-- Name: people_db_person_race_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: david
--
ALTER SEQUENCE public.people_db_person_race_id_seq OWNED BY public.people_db_person_race.id;
--
-- Name: people_db_personevent; Type: TABLE; Schema: public; Owner: david
--
CREATE TABLE public.people_db_personevent (
    pgh_id integer NOT NULL,
    pgh_created_at timestamp with time zone NOT NULL,
    pgh_label text NOT NULL,
    id integer NOT NULL,
    date_created timestamp with time zone NOT NULL,
    date_modified timestamp with time zone NOT NULL,
    date_completed timestamp with time zone,
    fjc_id integer,
    slug character varying(158) NOT NULL,
    name_first character varying(50) NOT NULL,
    name_middle character varying(50) NOT NULL,
    name_last character varying(50) NOT NULL,
    name_suffix character varying(5) NOT NULL,
    date_dob date,
    date_granularity_dob character varying(15) NOT NULL,
    date_dod date,
    date_granularity_dod character varying(15) NOT NULL,
    dob_city character varying(50) NOT NULL,
    dob_state character varying(2) NOT NULL,
    dob_country character varying(50) NOT NULL,
    dod_city character varying(50) NOT NULL,
    dod_state character varying(2) NOT NULL,
    dod_country character varying(50) NOT NULL,
    gender character varying(2) NOT NULL,
    religion character varying(30) NOT NULL,
    ftm_total_received double precision,
    ftm_eid character varying(30),
    has_photo boolean NOT NULL,
    is_alias_of_id integer,
    pgh_context_id uuid,
    pgh_obj_id integer NOT NULL
);
ALTER TABLE public.people_db_personevent OWNER TO david;
--
-- Name: people_db_personevent_pgh_id_seq; Type: SEQUENCE; Schema: public; Owner: david
--
CREATE SEQUENCE public.people_db_personevent_pgh_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.people_db_personevent_pgh_id_seq OWNER TO david;
--
-- Name: people_db_personevent_pgh_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: david
--
ALTER SEQUENCE public.people_db_personevent_pgh_id_seq OWNED BY public.people_db_personevent.pgh_id;
--
-- Name: people_db_personraceevent; Type: TABLE; Schema: public; Owner: david
--
CREATE TABLE public.people_db_personraceevent (
    pgh_id integer NOT NULL,
    pgh_created_at timestamp with time zone NOT NULL,
    pgh_label text NOT NULL,
    id integer NOT NULL,
    person_id integer NOT NULL,
    pgh_context_id uuid,
    race_id integer NOT NULL
);
ALTER TABLE public.people_db_personraceevent OWNER TO david;
--
-- Name: people_db_personraceevent_pgh_id_seq; Type: SEQUENCE; Schema: public; Owner: david
--
CREATE SEQUENCE public.people_db_personraceevent_pgh_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.people_db_personraceevent_pgh_id_seq OWNER TO david;
--
-- Name: people_db_personraceevent_pgh_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: david
--
ALTER SEQUENCE public.people_db_personraceevent_pgh_id_seq OWNED BY public.people_db_personraceevent.pgh_id;
-- 

------------------------------------------------------------------------------------
--
-- Name: people_db_school; Type: TABLE; Schema: public; Owner: david
--
CREATE TABLE public.people_db_school (
    id integer NOT NULL,
    date_created timestamp with time zone NOT NULL,
    date_modified timestamp with time zone NOT NULL,
    name character varying(120) NOT NULL,
    ein integer,
    is_alias_of_id integer
);
ALTER TABLE public.people_db_school OWNER TO david;

-- echo "Loading people-db-schools-2023-12-04.csv to database"
COPY public.people_db_school (
	       id, date_created, date_modified, name, ein, is_alias_of_id
	   ) FROM '/Volumes/aspen_cove/data/courtlistener/people-db-schools-2023-12-04.csv' WITH (FORMAT csv, ENCODING utf8, HEADER);;

--
-- Name: people_db_school_id_seq; Type: SEQUENCE; Schema: public; Owner: david
--
CREATE SEQUENCE public.people_db_school_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.people_db_school_id_seq OWNER TO david;
--
-- Name: people_db_school_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: david
--
ALTER SEQUENCE public.people_db_school_id_seq OWNED BY public.people_db_school.id;
--
-- Name: people_db_schoolevent; Type: TABLE; Schema: public; Owner: david
--
CREATE TABLE public.people_db_schoolevent (
    pgh_id integer NOT NULL,
    pgh_created_at timestamp with time zone NOT NULL,
    pgh_label text NOT NULL,
    id integer NOT NULL,
    date_created timestamp with time zone NOT NULL,
    date_modified timestamp with time zone NOT NULL,
    name character varying(120) NOT NULL,
    ein integer,
    is_alias_of_id integer,
    pgh_context_id uuid,
    pgh_obj_id integer NOT NULL
);
ALTER TABLE public.people_db_schoolevent OWNER TO david;
--
-- Name: people_db_schoolevent_pgh_id_seq; Type: SEQUENCE; Schema: public; Owner: david
--
CREATE SEQUENCE public.people_db_schoolevent_pgh_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.people_db_schoolevent_pgh_id_seq OWNER TO david;
--
-- Name: people_db_schoolevent_pgh_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: david
--
ALTER SEQUENCE public.people_db_schoolevent_pgh_id_seq OWNED BY public.people_db_schoolevent.pgh_id;

------------------------------------------------------------------------------------

--
-- Name: people_db_position; Type: TABLE; Schema: public; Owner: david
--

CREATE TABLE public.people_db_position (
    id integer NOT NULL,
    position_type character varying(20),
    job_title character varying(100) NOT NULL,
    organization_name character varying(120),
    date_created timestamp with time zone NOT NULL,
    date_modified timestamp with time zone NOT NULL,
    date_nominated date,
    date_elected date,
    date_recess_appointment date,
    date_referred_to_judicial_committee date,
    date_judicial_committee_action date,
    date_hearing date,
    date_confirmation date,
    date_start date,
    date_granularity_start character varying(15) NOT NULL,
    date_retirement date,
    date_termination date,
    date_granularity_termination character varying(15) NOT NULL,
    judicial_committee_action character varying(20) NOT NULL,
    nomination_process character varying(20) NOT NULL,
    voice_vote boolean,
    votes_yes integer,
    votes_no integer,
    how_selected character varying(20) NOT NULL,
    termination_reason character varying(25) NOT NULL,
    court_id character varying(15),
    person_id integer,
    school_id integer,
    appointer_id integer,
    predecessor_id integer,
    supervisor_id integer,
    vote_type character varying(2) NOT NULL,
    votes_no_percent double precision,
    votes_yes_percent double precision,
    location_city character varying(50) NOT NULL,
    location_state character varying(2) NOT NULL,
    has_inferred_values boolean NOT NULL,
    sector smallint,
    CONSTRAINT people_db_position_votes_no_check CHECK ((votes_no >= 0)),
    CONSTRAINT people_db_position_votes_yes_check CHECK ((votes_yes >= 0))
);
ALTER TABLE public.people_db_position OWNER TO david;
-- echo "Loading people-db-positions-2023-12-04.csv to database"
COPY public.people_db_position ( id, date_created, date_modified,
     position_type, job_title, sector, organization_name,
     location_city, location_state, date_nominated, date_elected,
     date_recess_appointment, date_referred_to_judicial_committee,
     date_judicial_committee_action, judicial_committee_action,
     date_hearing, date_confirmation, date_start,
     date_granularity_start, date_termination, termination_reason,
     date_granularity_termination, date_retirement,
     nomination_process, vote_type, voice_vote, votes_yes, votes_no,
     votes_yes_percent, votes_no_percent, how_selected,
     has_inferred_values, appointer_id, court_id, person_id,
     predecessor_id, school_id, supervisor_id ) FROM
     '/Volumes/aspen_cove/data/courtlistener/people-db-positions-2023-12-04.csv'
     WITH (FORMAT csv, ENCODING utf8, HEADER);


--
-- Name: people_db_position_id_seq; Type: SEQUENCE; Schema: public; Owner: david
--
CREATE SEQUENCE public.people_db_position_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.people_db_position_id_seq OWNER TO david;
--
-- Name: people_db_position_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: david
--
ALTER SEQUENCE public.people_db_position_id_seq OWNED BY public.people_db_position.id;
--
-- Name: people_db_positionevent; Type: TABLE; Schema: public; Owner: david
--
CREATE TABLE public.people_db_positionevent (
    pgh_id integer NOT NULL,
    pgh_created_at timestamp with time zone NOT NULL,
    pgh_label text NOT NULL,
    id integer NOT NULL,
    date_created timestamp with time zone NOT NULL,
    date_modified timestamp with time zone NOT NULL,
    position_type character varying(20),
    job_title character varying(100) NOT NULL,
    sector smallint,
    organization_name character varying(120),
    location_city character varying(50) NOT NULL,
    location_state character varying(2) NOT NULL,
    date_nominated date,
    date_elected date,
    date_recess_appointment date,
    date_referred_to_judicial_committee date,
    date_judicial_committee_action date,
    judicial_committee_action character varying(20) NOT NULL,
    date_hearing date,
    date_confirmation date,
    date_start date,
    date_granularity_start character varying(15) NOT NULL,
    date_termination date,
    termination_reason character varying(25) NOT NULL,
    date_granularity_termination character varying(15) NOT NULL,
    date_retirement date,
    nomination_process character varying(20) NOT NULL,
    vote_type character varying(2) NOT NULL,
    voice_vote boolean,
    votes_yes integer,
    votes_no integer,
    votes_yes_percent double precision,
    votes_no_percent double precision,
    how_selected character varying(20) NOT NULL,
    has_inferred_values boolean NOT NULL,
    appointer_id integer,
    court_id character varying(15),
    person_id integer,
    pgh_context_id uuid,
    pgh_obj_id integer NOT NULL,
    predecessor_id integer,
    school_id integer,
    supervisor_id integer,
    CONSTRAINT people_db_positionevent_votes_no_check CHECK ((votes_no >= 0)),
    CONSTRAINT people_db_positionevent_votes_yes_check CHECK ((votes_yes >= 0))
);
ALTER TABLE public.people_db_positionevent OWNER TO david;
--
-- Name: people_db_positionevent_pgh_id_seq; Type: SEQUENCE; Schema: public; Owner: david
--
CREATE SEQUENCE public.people_db_positionevent_pgh_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.people_db_positionevent_pgh_id_seq OWNER TO david;
--
-- Name: people_db_positionevent_pgh_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: david
--
ALTER SEQUENCE public.people_db_positionevent_pgh_id_seq OWNED BY public.people_db_positionevent.pgh_id;

------------------------------------------------------------------------------------
--
-- Name: people_db_retentionevent; Type: TABLE; Schema: public; Owner: david
--
CREATE TABLE public.people_db_retentionevent (
    id integer NOT NULL,
    date_created timestamp with time zone NOT NULL,
    date_modified timestamp with time zone NOT NULL,
    retention_type character varying(10) NOT NULL,
    date_retention date NOT NULL,
    votes_yes integer,
    votes_no integer,
    unopposed boolean,
    won boolean,
    position_id integer,
    votes_no_percent double precision,
    votes_yes_percent double precision,
    CONSTRAINT people_db_retentionevent_votes_no_check CHECK ((votes_no >= 0)),
    CONSTRAINT people_db_retentionevent_votes_yes_check CHECK ((votes_yes >= 0))
);
ALTER TABLE public.people_db_retentionevent OWNER TO david;

-- echo "Loading people-db-retention-events-2023-12-04.csv to database"
COPY public.people_db_retentionevent ( id, date_created,
     date_modified, retention_type, date_retention, votes_yes,
     votes_no, votes_yes_percent, votes_no_percent, unopposed, won,
     position_id ) FROM
     '/Volumes/aspen_cove/data/courtlistener/people-db-retention-events-2023-12-04.csv'
     WITH (FORMAT csv, ENCODING utf8, HEADER);

--
-- Name: people_db_retentionevent_id_seq; Type: SEQUENCE; Schema: public; Owner: david
--
CREATE SEQUENCE public.people_db_retentionevent_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.people_db_retentionevent_id_seq OWNER TO david;
--
-- Name: people_db_retentionevent_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: david
--
ALTER SEQUENCE public.people_db_retentionevent_id_seq OWNED BY public.people_db_retentionevent.id;
--
-- Name: people_db_retentioneventevent; Type: TABLE; Schema: public; Owner: david
--
CREATE TABLE public.people_db_retentioneventevent (
    pgh_id integer NOT NULL,
    pgh_created_at timestamp with time zone NOT NULL,
    pgh_label text NOT NULL,
    id integer NOT NULL,
    date_created timestamp with time zone NOT NULL,
    date_modified timestamp with time zone NOT NULL,
    retention_type character varying(10) NOT NULL,
    date_retention date NOT NULL,
    votes_yes integer,
    votes_no integer,
    votes_yes_percent double precision,
    votes_no_percent double precision,
    unopposed boolean,
    won boolean,
    pgh_context_id uuid,
    pgh_obj_id integer NOT NULL,
    position_id integer,
    CONSTRAINT people_db_retentioneventevent_votes_no_check CHECK ((votes_no >= 0)),
    CONSTRAINT people_db_retentioneventevent_votes_yes_check CHECK ((votes_yes >= 0))
);
ALTER TABLE public.people_db_retentioneventevent OWNER TO david;
--
-- Name: people_db_retentioneventevent_pgh_id_seq; Type: SEQUENCE; Schema: public; Owner: david
--
CREATE SEQUENCE public.people_db_retentioneventevent_pgh_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.people_db_retentioneventevent_pgh_id_seq OWNER TO david;
--
-- Name: people_db_retentioneventevent_pgh_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: david
--
ALTER SEQUENCE public.people_db_retentioneventevent_pgh_id_seq OWNED BY public.people_db_retentioneventevent.pgh_id;

------------------------------------------------------------------------------------

--
-- Name: people_db_education; Type: TABLE; Schema: public; Owner: david
--
CREATE TABLE public.people_db_education (
    id integer NOT NULL,
    date_created timestamp with time zone NOT NULL,
    date_modified timestamp with time zone NOT NULL,
    degree_detail character varying(100) NOT NULL,
    degree_year smallint,
    person_id integer,
    school_id integer NOT NULL,
    degree_level character varying(4) NOT NULL,
    CONSTRAINT people_db_education_degree_year_check CHECK ((degree_year >= 0))
);
ALTER TABLE public.people_db_education OWNER TO david;

-- echo "Loading people-db-educations-2023-12-04.csv to database"
COPY public.people_db_education ( id, date_created, date_modified,
     degree_level, degree_detail, degree_year, person_id, school_id )
     FROM
     '/Volumes/aspen_cove/data/courtlistener/people-db-educations-2023-12-04.csv'
     WITH (FORMAT csv, ENCODING utf8, HEADER);

--
-- Name: people_db_education_id_seq; Type: SEQUENCE; Schema: public; Owner: david
--
CREATE SEQUENCE public.people_db_education_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.people_db_education_id_seq OWNER TO david;
--
-- Name: people_db_education_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: david
--
ALTER SEQUENCE public.people_db_education_id_seq OWNED BY public.people_db_education.id;
--
-- Name: people_db_educationevent; Type: TABLE; Schema: public; Owner: david
--
CREATE TABLE public.people_db_educationevent (
    pgh_id integer NOT NULL,
    pgh_created_at timestamp with time zone NOT NULL,
    pgh_label text NOT NULL,
    id integer NOT NULL,
    date_created timestamp with time zone NOT NULL,
    date_modified timestamp with time zone NOT NULL,
    degree_level character varying(4) NOT NULL,
    degree_detail character varying(100) NOT NULL,
    degree_year smallint,
    person_id integer,
    pgh_context_id uuid,
    pgh_obj_id integer NOT NULL,
    school_id integer NOT NULL,
    CONSTRAINT people_db_educationevent_degree_year_check CHECK ((degree_year >= 0))
);
ALTER TABLE public.people_db_educationevent OWNER TO david;
--
-- Name: people_db_educationevent_pgh_id_seq; Type: SEQUENCE; Schema: public; Owner: david
--
CREATE SEQUENCE public.people_db_educationevent_pgh_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.people_db_educationevent_pgh_id_seq OWNER TO david;
--
-- Name: people_db_educationevent_pgh_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: david
--
ALTER SEQUENCE public.people_db_educationevent_pgh_id_seq OWNED BY public.people_db_educationevent.pgh_id;

------------------------------------------------------------------------------------

--
-- Name: people_db_politicalaffiliation; Type: TABLE; Schema: public; Owner: david
--
CREATE TABLE public.people_db_politicalaffiliation (
    id integer NOT NULL,
    date_created timestamp with time zone NOT NULL,
    date_modified timestamp with time zone NOT NULL,
    political_party character varying(5) NOT NULL,
    source character varying(5) NOT NULL,
    date_start date,
    date_granularity_start character varying(15) NOT NULL,
    date_end date,
    date_granularity_end character varying(15) NOT NULL,
    person_id integer
);
ALTER TABLE public.people_db_politicalaffiliation OWNER TO david;

-- echo "Loading people-db-political-affiliations-2023-12-04.csv to database"
COPY public.people_db_politicalaffiliation ( id, date_created,
     date_modified, political_party, source, date_start,
     date_granularity_start, date_end, date_granularity_end, person_id
     ) FROM
     '/Volumes/aspen_cove/data/courtlistener/people-db-political-affiliations-2023-12-04.csv'
     WITH (FORMAT csv, ENCODING utf8, HEADER);


--
-- Name: people_db_politicalaffiliation_id_seq; Type: SEQUENCE; Schema: public; Owner: david
--
CREATE SEQUENCE public.people_db_politicalaffiliation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.people_db_politicalaffiliation_id_seq OWNER TO david;
--
-- Name: people_db_politicalaffiliation_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: david
--
ALTER SEQUENCE public.people_db_politicalaffiliation_id_seq OWNED BY public.people_db_politicalaffiliation.id;
--
-- Name: people_db_politicalaffiliationevent; Type: TABLE; Schema: public; Owner: david
--
CREATE TABLE public.people_db_politicalaffiliationevent (
    pgh_id integer NOT NULL,
    pgh_created_at timestamp with time zone NOT NULL,
    pgh_label text NOT NULL,
    id integer NOT NULL,
    date_created timestamp with time zone NOT NULL,
    date_modified timestamp with time zone NOT NULL,
    political_party character varying(5) NOT NULL,
    source character varying(5) NOT NULL,
    date_start date,
    date_granularity_start character varying(15) NOT NULL,
    date_end date,
    date_granularity_end character varying(15) NOT NULL,
    person_id integer,
    pgh_context_id uuid,
    pgh_obj_id integer NOT NULL
);
ALTER TABLE public.people_db_politicalaffiliationevent OWNER TO david;
--
-- Name: people_db_politicalaffiliationevent_pgh_id_seq; Type: SEQUENCE; Schema: public; Owner: david
--
CREATE SEQUENCE public.people_db_politicalaffiliationevent_pgh_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.people_db_politicalaffiliationevent_pgh_id_seq OWNER TO david;
--
-- Name: people_db_politicalaffiliationevent_pgh_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: david
--
ALTER SEQUENCE public.people_db_politicalaffiliationevent_pgh_id_seq OWNED BY public.people_db_politicalaffiliationevent.pgh_id;

------------------------------------------------------------------------------------
--
-- Name: people_db_race; Type: TABLE; Schema: public; Owner: david
--
CREATE TABLE public.people_db_race (
    id integer NOT NULL,
    race character varying(5) NOT NULL
);
ALTER TABLE public.people_db_race OWNER TO david;

-- echo "Loading people-db-races-2023-12-04.csv to database"

COPY public.people_db_person_race ( id, person_id, race_id ) FROM
     '/Volumes/aspen_cove/data/courtlistener/people-db-races-2023-12-04.csv'
     WITH (FORMAT csv, ENCODING utf8, HEADER);


--
-- Name: people_db_race_id_seq; Type: SEQUENCE; Schema: public; Owner: david
--
CREATE SEQUENCE public.people_db_race_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.people_db_race_id_seq OWNER TO david;
--
-- Name: people_db_race_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: david
--
ALTER SEQUENCE public.people_db_race_id_seq OWNED BY public.people_db_race.id;
--
-- Name: people_db_raceevent; Type: TABLE; Schema: public; Owner: david
--
CREATE TABLE public.people_db_raceevent (
    pgh_id integer NOT NULL,
    pgh_created_at timestamp with time zone NOT NULL,
    pgh_label text NOT NULL,
    id integer NOT NULL,
    race character varying(5) NOT NULL,
    pgh_context_id uuid,
    pgh_obj_id integer NOT NULL
);
ALTER TABLE public.people_db_raceevent OWNER TO david;
--
-- Name: people_db_raceevent_pgh_id_seq; Type: SEQUENCE; Schema: public; Owner: david
--
CREATE SEQUENCE public.people_db_raceevent_pgh_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.people_db_raceevent_pgh_id_seq OWNER TO david;
--
-- Name: people_db_raceevent_pgh_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: david
--
ALTER SEQUENCE public.people_db_raceevent_pgh_id_seq OWNED BY public.people_db_raceevent.pgh_id;

------------------------------------------------------------------------------------

-- echo "Loading financial-disclosures-2023-12-04.csv to database"
COPY public.disclosures_financialdisclosure (
	       id, date_created, date_modified, year, download_filepath, filepath, thumbnail,
	       thumbnail_status, page_count, sha1, report_type, is_amended, addendum_content_raw,
	       addendum_redacted, has_been_extracted, person_id
	   ) FROM '/Volumes/aspen_cove/data/courtlistener/financial-disclosures-2023-12-04.csv' WITH (FORMAT csv, ENCODING utf8, HEADER);
------------------------------------------------------------------------------------

-- echo "Loading financial-disclosure-investments-2023-12-04.csv to database"
COPY public.disclosures_investment (
	       id, date_created, date_modified, page_number, description, redacted,
	       income_during_reporting_period_code, income_during_reporting_period_type,
	       gross_value_code, gross_value_method,
	       transaction_during_reporting_period, transaction_date_raw,
	       transaction_date, transaction_value_code, transaction_gain_code,
	       transaction_partner, has_inferred_values, financial_disclosure_id
	   ) FROM '/Volumes/aspen_cove/data/courtlistener/financial-disclosure-investments-2023-12-04.csv' WITH (FORMAT csv, ENCODING utf8, HEADER);
------------------------------------------------------------------------------------

-- echo "Loading financial-disclosures-positions-2023-12-04.csv to database"
COPY public.disclosures_position (
	       id, date_created, date_modified, position, organization_name,
	       redacted, financial_disclosure_id
	   ) FROM '/Volumes/aspen_cove/data/courtlistener/financial-disclosures-positions-2023-12-04.csv' WITH (FORMAT csv, ENCODING utf8, HEADER);
------------------------------------------------------------------------------------

-- echo "Loading financial-disclosures-agreements-2023-12-04.csv to database"
COPY public.disclosures_agreement (
	       id, date_created, date_modified, date_raw, parties_and_terms,
	       redacted, financial_disclosure_id
	   ) FROM '/Volumes/aspen_cove/data/courtlistener/financial-disclosures-agreements-2023-12-04.csv' WITH (FORMAT csv, ENCODING utf8, HEADER);
------------------------------------------------------------------------------------

-- echo "Loading financial-disclosures-non-investment-income-2023-12-04.csv to database"
COPY public.disclosures_noninvestmentincome (
	       id, date_created, date_modified, date_raw, source_type,
	       income_amount, redacted, financial_disclosure_id
	   ) FROM '/Volumes/aspen_cove/data/courtlistener/financial-disclosures-non-investment-income-2023-12-04.csv' WITH (FORMAT csv, ENCODING utf8, HEADER);
------------------------------------------------------------------------------------

-- echo "Loading financial-disclosures-spousal-income-2023-12-04.csv to database"
COPY public.disclosures_spouseincome (
	       id, date_created, date_modified, source_type, date_raw, redacted,
	       financial_disclosure_id
	   ) FROM '/Volumes/aspen_cove/data/courtlistener/financial-disclosures-spousal-income-2023-12-04.csv' WITH (FORMAT csv, ENCODING utf8, HEADER);
------------------------------------------------------------------------------------

-- echo "Loading financial-disclosures-reimbursements-2023-12-04.csv to database"
COPY public.disclosures_reimbursement (
	       id, date_created, date_modified, source, date_raw, location,
	       purpose, items_paid_or_provided, redacted, financial_disclosure_id
	   ) FROM '/Volumes/aspen_cove/data/courtlistener/financial-disclosures-reimbursements-2023-12-04.csv' WITH (FORMAT csv, ENCODING utf8, HEADER);
------------------------------------------------------------------------------------

-- echo "Loading financial-disclosures-gifts-2023-12-04.csv to database"
COPY public.disclosures_gift (
	       id, date_created, date_modified, source, description, value,
	       redacted, financial_disclosure_id
	   ) FROM '/Volumes/aspen_cove/data/courtlistener/financial-disclosures-gifts-2023-12-04.csv' WITH (FORMAT csv, ENCODING utf8, HEADER);
------------------------------------------------------------------------------------

-- echo "Loading financial-disclosures-debts-2023-12-04.csv to database"

COPY public.disclosures_debt (
	       id, date_created, date_modified, creditor_name, description,
	       value_code, redacted, financial_disclosure_id
	   ) FROM '/Volumes/aspen_cove/data/courtlistener/financial-disclosures-debts-2023-12-04.csv' WITH (FORMAT csv, ENCODING utf8, HEADER);
